In [18]:
import numpy as np
import pandas as pd

In [19]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [37]:
df = pd.read_csv('gurgaon_properties.csv')

In [38]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2149,1 BHK Flat in Sector 95 Gurgaon,flat,ramsons kshitij,0.22,6470.0,340.0,Super Built up area 340(31.59 sq.m.),1,1,1,not available,"Sector 95 Gurgaon, Gurgaon, Haryana",2.0,NaN,0 to 1 Year Old,"['Bangali Clinic', 'Yadav Clinic', 'Dr. J. S. ...",Residential apartment for sell.Located in sect...,[],NaN,"['Management3.5 out of 5', 'Green Area4 out of..."
515,3 BHK Flat in Sector 92 Gurgaon,flat,gls avenue 51,0.39,6077.0,642.0,Carpet area: 641.74 (59.62 sq.m.),3,3,3+,not available,"Sector-92,gurgaon, Sector 92 Gurgaon, Gurgaon,...",6.0,North,1 to 5 Year Old,"['Yaduvanshi Shiksha Niketan Sector- 92', 'Aar...",Located in the popular residential address of ...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
2037,4 BHK Flat in Sector 92 Gurgaon,flat,sare green parc phase 3,0.95,4856.0,1956.0,Super Built up area 1956(181.72 sq.m.),4,3,3,not available,"Sector 92 Gurgaon, Gurgaon, Haryana",4.0,North,5 to 10 Year Old,"['Huda Metro Station', 'Sector Road', 'Delhi-J...",Ready to move in property.\nHealth and educati...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
3048,3 BHK Flat in Sector 65 Gurgaon,flat,m3m golfestate,5.30,24211.0,2189.0,Super Built up area 2850(264.77 sq.m.)Carpet a...,3,3,3,servant room,"Sector 65 Gurgaon, Gurgaon, Haryana",38.0,North-East,5 to 10 Year Old,"['Sector 54 Chowk Metro Station', 'Sahara Mall...",M3m very luxury society on road,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '4 Geys...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
2967,2 BHK Flat in Sector 103 Gurgaon,flat,signature global grand iva,0.50,6667.0,750.0,Built Up area: 750 (69.68 sq.m.)Carpet area: 6...,2,2,0,not available,"Sector 103, Sector 103 Gurgaon, Gurgaon, Haryana",10.0,North,undefined,"['Dwaraka Expy, Tikampur Village', 'Sector 108...",Best in class property available at sector 103...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area5 out of 5', 'Construction5 out of..."

In [39]:
df.shape

(3961, 20)

In [40]:
df.duplicated().sum()

np.int64(0)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [42]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [43]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 79 Gurgaon,flat,godrej,1.93,8532.0,2262.0,Super Built up area 2262(210.15 sq.m.),3,4,3+,servant room,"Aa2, Sector 79 Gurgaon, Gurgaon, Haryana",5.0,East,1 to 5 Year Old,"['Vatika Town Square-INXT', 'Naurangpur Road',...","This 3 bhk flat is located in godrej 101, whic...",NaN,"['Centrally Air Conditioned', 'Security / Fire...","['Green Area5 out of 5', 'Construction5 out of..."
1,3 BHK Flat in Sector 60 Gurgaon,flat,ireo skyon,3.00,12484.0,2403.0,Super Built up area 2403(223.25 sq.m.)Built Up...,3,3,3,servant room,"507, Sector 60 Gurgaon, Gurgaon, Haryana",5.0,North-East,1 to 5 Year Old,"['Sector 55-56 Metro', 'Golf Course Extension'...",Located in the popular residential address of ...,"['4 Wardrobe', '1 Water Purifier', '1 Exhaust ...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
2,2 BHK Flat in Sector 89 Gurgaon,flat,greenopolis,0.65,5195.0,1251.0,Carpet area: 1251 (116.22 sq.m.),2,2,2,not available,"Sector 89 Gurgaon, Gurgaon, Haryana",15.0,NaN,Aug 2024,"['Orris Community Center', 'Indian Oil', 'Essa...",Greenopolis 2bhk on high floor in tower 5,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,4 Bedroom House for sale in Subhash Nagar,house,independent,0.90,13333.0,675.0,Built Up area: 675 (62.71 sq.m.),4,4,0,not available,"Subhash Nagar, Sector 12a, Subhash Nagar, Gurg...",2.0,NaN,undefined,NaN,Best in class property available at subhash na...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment3.5 out of 5', 'Lifestyle4.5 out ..."
4,4 BHK Flat in Sector 72 Gurgaon,flat,tata primanti,3.20,12190.0,2625.0,Super Built up area 2625(243.87 sq.m.)Built Up...,4,4,3+,servant room,"1302, Sector 72 Gurgaon, Gurgaon, Haryana",8.0,North,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...","Situated in sector 72 gurgaon, tata primanti i...","['6 Fan', '4 Geyser', '1 Stove', '12 Light', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."

In [44]:
df.insert(loc=3, column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [45]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 79 Gurgaon,flat,godrej,Sector 79,1.93,8532.0,2262.0,Super Built up area 2262(210.15 sq.m.),3,4,3+,servant room,"Aa2, Sector 79 Gurgaon, Gurgaon, Haryana",5.0,East,1 to 5 Year Old,"['Vatika Town Square-INXT', 'Naurangpur Road',...","This 3 bhk flat is located in godrej 101, whic...",NaN,"['Centrally Air Conditioned', 'Security / Fire...","['Green Area5 out of 5', 'Construction5 out of..."
1,3 BHK Flat in Sector 60 Gurgaon,flat,ireo skyon,Sector 60,3.00,12484.0,2403.0,Super Built up area 2403(223.25 sq.m.)Built Up...,3,3,3,servant room,"507, Sector 60 Gurgaon, Gurgaon, Haryana",5.0,North-East,1 to 5 Year Old,"['Sector 55-56 Metro', 'Golf Course Extension'...",Located in the popular residential address of ...,"['4 Wardrobe', '1 Water Purifier', '1 Exhaust ...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
2,2 BHK Flat in Sector 89 Gurgaon,flat,greenopolis,Sector 89,0.65,5195.0,1251.0,Carpet area: 1251 (116.22 sq.m.),2,2,2,not available,"Sector 89 Gurgaon, Gurgaon, Haryana",15.0,NaN,Aug 2024,"['Orris Community Center', 'Indian Oil', 'Essa...",Greenopolis 2bhk on high floor in tower 5,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,4 Bedroom House for sale in Subhash Nagar,house,independent,Subhash Nagar,0.90,13333.0,675.0,Built Up area: 675 (62.71 sq.m.),4,4,0,not available,"Subhash Nagar, Sector 12a, Subhash Nagar, Gurg...",2.0,NaN,undefined,NaN,Best in class property available at subhash na...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment3.5 out of 5', 'Lifestyle4.5 out ..."
4,4 BHK Flat in Sector 72 Gurgaon,flat,tata primanti,Sector 72,3.20,12190.0,2625.0,Super Built up area 2625(243.87 sq.m.)Built Up...,4,4,3+,servant room,"1302, Sector 72 Gurgaon, Gurgaon, Haryana",8.0,North,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...","Situated in sector 72 gurgaon, tata primanti i...","['6 Fan', '4 Geyser', '1 Stove', '12 Light', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."

In [47]:
df['sector'] = df['sector'].str.lower()

In [48]:
df.head(2)

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 79 Gurgaon,flat,godrej,sector 79,1.93,8532.0,2262.0,Super Built up area 2262(210.15 sq.m.),3,4,3+,servant room,"Aa2, Sector 79 Gurgaon, Gurgaon, Haryana",5.0,East,1 to 5 Year Old,"['Vatika Town Square-INXT', 'Naurangpur Road',...","This 3 bhk flat is located in godrej 101, whic...",NaN,"['Centrally Air Conditioned', 'Security / Fire...","['Green Area5 out of 5', 'Construction5 out of..."
1,3 BHK Flat in Sector 60 Gurgaon,flat,ireo skyon,sector 60,3.00,12484.0,2403.0,Super Built up area 2403(223.25 sq.m.)Built Up...,3,3,3,servant room,"507, Sector 60 Gurgaon, Gurgaon, Haryana",5.0,North-East,1 to 5 Year Old,"['Sector 55-56 Metro', 'Golf Course Extension'...",Located in the popular residential address of ...,"['4 Wardrobe', '1 Water Purifier', '1 Exhaust ...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."

In [49]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 65                                                     90
sector 90                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 48                                                     56
sector 89                                                     56
sector 70a                                                    54
sector 70                                                     53
nirvana country                                               53
sector 37c                                                    53
sector-33 sohna                                               51
sector 84                                                     51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 2                                                   43
sector 113                                                    43
dlf phase 1                                                   43
sector 61                                                     42
sector 82                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 54                                                     27
laxman vihar                                                  27
sector 71                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
sector 67a                                                    22
sector 111                                                    22
dlf phase 3                                                   22
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 62                                                     17
sector 91                                                     17
sector 99                                                     16
sushant lok phase 3                                           16
sector 110                                                    16
sector 60                                                     15
sector 63                                                     15
sector 14                                                     15
sector 53                                                     14
rajendra park                                                 14
sector 3                                                      14
gwal pahari                                                   14
sector 76                                                     14
sector 1 imt manesar                                          14
sector 52                                                     14
dlf phase 5                                                   14
sector 46                                                     13
sector 36a                                                    13
laxman vihar phase 2                                          13
sector 93                                                     12
sector 38                                                     12
sector 39                                                     12
uppals southend                                               12
sohna road                                                    12
sector 31                                                     12
sector 50                                                     12
sector 9a                                                     11
ashok vihar phase 3 extension                                 11
sector 47                                                     11
sector 1a imt manesar                                         10
sector 7                                                      10
ashok vihar phase 2                                            9
south city 1                                                   9
sector 4                                                       9
sector 55                                                      9
sector 95a                                                     9
sector 43                                                      8
mehrauli  road                                                 8
palam vihar extension                                          8
sector 57                                                      8
sector 89 a                                                    8
sector 59                                                      8
malibu town                                                    8
dwarka expressway                                              8
sector 40                                                      8
c block sushant lok phase 1                                    8
sector 10a                                                     8
sector 26                                                      7
mianwali colony                                                7
new colony                                                     7
surat nagar 1                                                  7
sector 51                                                      7
sector 11                                                      7
sector 58                                                      7
sector 36 sohna                                                7
rajiv nagar                                                    6
sector 5                                                       6
ashok vihar                                                    6
jyoti park                                                     6
jacobpura                                                      6
sector 1                                                       6
saraswati vihar                                                5
new palam vihar                                                5
subhash nagar                                                  5
greenwood city                                                 5
ansal plaza                                                    5
sector 23a                                                     5
sector 9                                                       5
dayanand colony                                                5
sector 28                                                      5
sector 2                                                       5
manesar                                                        5
chakkarpur                                                     5
sector 105                                                     5
sector 80                                                      5
arjun nagar                                                    5
sushant lok phase 2                                            5
sector 30                                                      5
vishnu garden                                                  4
bhim nagar                                                     4
sector 45                                                      4
adarsh nagar                                                   4
valley view estate                                             4
shivaji nagar                                                  4
sector 3a                                                      4
baldev nagar                                                   4
devilal colony                                                 4
garhi harsaru                                                  4
surya vihar                                                    4
suncity                                                        4
imt manesar                                                    4
sector 12a                                                     4
bhondsi                                                        4
shivpuri                                                       4
sector 6                                                       4
sector 12                                                      4
sector 36                                                      4
madanpuri                                                      4
krishna colony                                                 4
ravi nagar                                                     4
sector 17                                                      4
new                                                            4
dharam colony                                                  4
sector 8                                                       3
prem nagar                                                     3
maruti kunj                                                    3
sector 23                                                      3
gandhi nagar                                                   3
sector 17a                                                     3
sector 15                                                      3
sector 73                                                      3
a block sushant lok phase 1                                    3
sector 88b                                                     3
sector 27                                                      3
b block sushant lok phase 1                                    3
patel nagar                                                    3
sector 17b                                                     3
shakti nagar                                                   3
laxmi garden                                                   3
mg road                                                        3
sector 110 a                                                   3
acharya puri                                                   2
lajpat nagar                                                   2
bissar                                                         2
mayfield garden                                                2
sheetla colony                                                 2
sector-2 sohna                                                 2
surat nagar phase 2                                            2
, delhi ncr                                                    2
hira nagar                                                     2
rosewood                                                       2
sector-11 sohna                                                2
sector 21                                                      2
block a surya vihar                                            2
samaspur                                                       2
sector 15 part 1                                               2
sispal vihar                                                   2
new palam vihar phase 2                                        2
shankar vihar                                                  2
nars                                                           2
pratap nagar                                                   2
west rajiv nagar                                               2
shanti nagar                                                   2
rajiv chowk                                                    2
sushant lok                                                    2
farukhnagar                                                    2
sector 41                                                      2
mohan nagar                                                    2
sector 15 part 2                                               2
daulatabad                                                     2
golf course ext road                                           2
ambience island                                                2
new basti                                                      2
golf course road                                               2
sohna  road                                                    2
iffco chowk                                                    2
sector 32                                                      2
surat nagar                                                    2
new palam vihar phase 1                                        2
bhawani enclave                                                2
faridabad road                                                 2
manohar nagar                                                  2
sector 24                                                      2
near sector 1 market                                           1
g block dlf city phase 1                                       1
damdma                                                         1
ram nagar                                                      1
urban estate, sector 5                                         1
sultanpur                                                      1
udyog vihar phase 1                                            1
naharpur rupa                                                  1
ansal's palam vihar                                            1
new colony, sector 7                                           1
civil l                                                        1
garauli kalan                                                  1
huda saraswati vihar                                           1
sector 21a faridabad                                           1
cyber city                                                     1
saraswati enclave                                              1
sector 13                                                      1
sector-7 hous                                                  1
near pataudi chowk                                             1
kanahi                                                         1
hsiidc plot sector 1 imt manesar                               1
shivji park colony                                             1
carterpuri village                                             1
ats marigold                                                   1
begampur khatola                                               1
heritage city                                                  1
block h ashok vihar phase iii extension                        1
om nagar                                                       1
sector 37a                                                     1
sector-35 sohna                                                1
khandsa                                                        1
jat colony,fazilpur/taj nagar road                             1
old delhi road, opp sector-14                                  1
sector-5 sohna                                                 1
tekchand nagar                                                 1
near nand hospital                                             1
sector 9b                                                      1
vir nagar                                                      1
hno 13 sagar enclave sura                                      1
bhora kalan                                                    1
v block dlf phase 3                                            1
ashok vihar phase i                                            1
rajiv colony                                                   1
anand garden, sector-105                                       1
sadar bazar                                                    1
sector-5 sheetla colony                                        1
sai kunj                                                       1
ashok vihar phase 3                                            1
sector 17c                                                     1
sector 37b                                                     1
rattan garden                                                  1
dhankot                                                        1
ravi nager basai road                                          1
nirvana country pocket h                                       1
near khandsa road                                              1
near euro                                                      1
laxman vihar, railway road,                                    1
sector 4 urban estate                                          1
alipur                                                         1
bhimgarh kheri phase 3                                         1
new jyoti park                                                 1
saroop garden rajendra park                                    1
pataudi road                                                   1
bptp                                                           1
mahavir pura                                                   1
kheri                                                          1
laxmna vihar, phase 2                                          1
gopal nagar, garhi ghasita, sonipat                            1
godrej aria , sector 79 ,                                      1
jacobpura near sadar bazar                                     1
sector 5 chowk                                                 1
lucknow                                                        1
block g sector-57                                              1
devi lal colony gali no 12 gurgaon nr omkar public school      1
mahalaxmi garden, rajendra place                               1
b1 block sector 57                                             1
sector 42                                                      1
park view                                                      1
part 3 sector 5                                                1
south city                                                     1
sec 3 bhim vihar part 1 bhimgher kheri                         1
Name: count, dtype: int64

In [50]:
df['sector'] = df['sector'].str.replace('dharam colony', 'sector 12')
df['sector'] = df['sector'].str.replace('krishna colony', 'sector 7')
df['sector'] = df['sector'].str.replace('suncity', 'sector 54')
df['sector'] = df['sector'].str.replace('prem nagar', 'sector 13')
df['sector'] = df['sector'].str.replace('mg road', 'sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar', 'sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden', 'sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar', 'sector 11')

In [51]:
df['sector'] = df['sector'].str.replace('baldev nagar', 'sector 7')
df['sector'] = df['sector'].str.replace('shivpuri', 'sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru', 'sector 17')
df['sector'] = df['sector'].str.replace('imt manesar', 'manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar', 'sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar', 'sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar', 'sector 6')
df['sector'] = df['sector'].str.replace('madanpuri', 'sector 7')

In [52]:
df['sector'] = df['sector'].str.replace('sarswati vihar', 'sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar', 'sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar', 'sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden', 'sector 105')
df['sector'] = df['sector'].str.replace('bhondsi', 'sector 11')
df['sector'] = df['sector'].str.replace('surya vihar', 'sector 21')
df['sector'] = df['sector'].str.replace('devilal colony', 'sector 9')
df['sector'] = df['sector'].str.replace('valley view estate', 'gwal pahari')

In [53]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [54]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [55]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [56]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [57]:
df['sector'].value_counts()

sector
sohna road                                                   163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 90                                                     90
sector 65                                                     90
sector 109                                                    88
sector 79                                                     80
sector 104                                                    73
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 50                                                     65
sector 107                                                    60
sector 108                                                    59
sector 56                                                     57
sector 95                                                     57
sector 48                                                     56
sector 89                                                     56
sector 2                                                      55
sector 70a                                                    54
sector 37c                                                    53
sector 70                                                     53
sector 43                                                     53
sector-33 sohna road                                          51
sector 84                                                     51
sector 26                                                     50
sector 67                                                     48
sector 49                                                     48
sector 66                                                     46
sector 103                                                    45
sector 25                                                     43
sector 113                                                    43
sector 28                                                     42
sector 61                                                     42
sector 82                                                     42
sector 7                                                      39
sector 106                                                    38
sector 4                                                      36
sector 99a                                                    32
sector 54                                                     31
sector 68                                                     30
sector 12                                                     30
sector 72                                                     29
sector 77                                                     29
sector 71                                                     27
sector 57                                                     24
sector 112                                                    24
sector 24                                                     24
sector 14                                                     23
sector 105                                                    23
sector 33                                                     23
sector 88a                                                    23
sector 67a                                                    22
sector 111                                                    22
sector 11                                                     21
sector 82a                                                    20
sector 22                                                     20
sector 3                                                      20
sector 78                                                     19
sector 47                                                     19
gwal pahari                                                   18
sector 74                                                     18
sector 63a                                                    18
sector 91                                                     17
sector 62                                                     17
sector 99                                                     16
sector 110                                                    16
sector 63                                                     15
sector 60                                                     15
sector 76                                                     14
sector 55                                                     14
sector 1 manesar                                              14
sector 53                                                     14
sector 52                                                     14
sector 46                                                     13
sector 9                                                      13
sector 36a                                                    13
sector 4 phase 2                                              13
sector 6                                                      13
sector 31                                                     12
sector 38                                                     12
sector 39                                                     12
sector 93                                                     12
sohna road road                                               12
sector 3 phase 3 extension                                    11
sector 41                                                     11
sector 9a                                                     11
sector 13                                                     10
sector 1a manesar                                             10
sector 3 phase 2                                               9
sector 45                                                      9
sector 95a                                                     9
manesar                                                        9
sector 23                                                      8
sector 59                                                      8
c block sector 43                                              8
sector 10a                                                     8
sector 40                                                      8
sector 17                                                      8
sector 8                                                       8
sector 2 extension                                             8
dwarka expressway                                              8
sector 89 a                                                    8
sector 51                                                      7
sector 58                                                      7
sector 36 sohna road                                           7
sector 5                                                       6
sector 1                                                       6
sector 21                                                      6
sector 23a                                                     5
sector 80                                                      5
sector 30                                                      5
saraswati vihar                                                5
new sector 2                                                   5
sector 36                                                      4
sector 12a                                                     4
new                                                            4
sector 3a                                                      4
maruti kunj                                                    3
a block sector 43                                              3
patel nagar                                                    3
sector 17b                                                     3
sector 27                                                      3
sector 88b                                                     3
sector 110 a                                                   3
b block sector 43                                              3
sector 15                                                      3
sector 73                                                      3
sector 17a                                                     3
mohan nagar                                                    2
nars                                                           2
rajiv chowk                                                    2
shankar vihar                                                  2
pratap nagar                                                   2
manohar nagar                                                  2
shanti nagar                                                   2
, delhi ncr                                                    2
mayfield garden                                                2
iffco chowk                                                    2
sohna road  road                                               2
golf course road                                               2
bissar                                                         2
sector-11 sohna road                                           2
sector-2 sohna road                                            2
faridabad road                                                 2
sector 32                                                      2
bhawani enclave                                                2
surat nagar                                                    2
sheetla colony                                                 2
block a sector 21                                              2
hira nagar                                                     2
surat nagar phase 2                                            2
acharya puri                                                   2
ambience island                                                2
golf course ext road                                           2
new basti                                                      2
sushant lok                                                    2
west sector 13                                                 2
farukhnagar                                                    2
rosewood                                                       2
sector 15 part 1                                               2
samaspur                                                       2
new sector 2 phase 2                                           2
sispal vihar                                                   2
new sector 2 phase 1                                           2
daulatabad                                                     2
lajpat nagar                                                   2
sector 15 part 2                                               2
naharpur rupa                                                  1
shivji park colony                                             1
sector 7, sector 7                                             1
damdma                                                         1
near sector 1 market                                           1
heritage city                                                  1
sector 9b                                                      1
tekchand nagar                                                 1
hsiidc plot sector 1 manesar                                   1
near pataudi chowk                                             1
ansal's sector 2                                               1
kanahi                                                         1
sector-7 hous                                                  1
sector-35 sohna road                                           1
khandsa                                                        1
sector-5 sohna road                                            1
sector-5 sheetla colony                                        1
sector 4 urban estate                                          1
sai kunj                                                       1
alipur                                                         1
sector 3 phase 3                                               1
begampur khatola                                               1
carterpuri village                                             1
sector 17c                                                     1
ats marigold                                                   1
v block sector 24                                              1
jat colony,fazilpur/taj nagar road                             1
block h sector 3 phase iii extension                           1
vir nagar                                                      1
bhora kalan                                                    1
hno 13 sagar enclave sura                                      1
old delhi road, opp sector-14                                  1
sector 37a                                                     1
near nand hospital                                             1
om nagar                                                       1
ravi nager basai road                                          1
rajiv colony                                                   1
anand garden, sector-105                                       1
sector 37b                                                     1
rattan garden                                                  1
mahavir pura                                                   1
near khandsa road                                              1
sector 50 pocket h                                             1
sector 4, railway road,                                        1
near euro                                                      1
sector 3 phase i                                               1
bhimgarh kheri phase 3                                         1
sadar bazar                                                    1
saroop garden sector 105                                       1
gopal nagar, garhi ghasita, sonipat                            1
laxmna vihar, phase 2                                          1
new sector 7                                                   1
bptp                                                           1
pataudi road                                                   1
dhankot                                                        1
godrej aria , sector 79 ,                                      1
g block dlf city phase 1                                       1
civil l                                                        1
garauli kalan                                                  1
cyber city                                                     1
saraswati enclave                                              1
urban estate, sector 5                                         1
udyog vihar phase 1                                            1
kheri                                                          1
ram nagar                                                      1
sector 21a faridabad                                           1
sultanpur                                                      1
huda saraswati vihar                                           1
sector 12 near sadar bazar                                     1
sector 5 chowk                                                 1
lucknow                                                        1
block g sector-57                                              1
devi lal colony gali no 12 gurgaon nr omkar public school      1
mahasector 11, rajendra place                                  1
b1 block sector 57                                             1
sector 42                                                      1
park view                                                      1
part 3 sector 5                                                1
south city                                                     1
sec 3 bhim vihar part 1 bhimgher kheri                         1
Name: count, dtype: int64

In [59]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [61]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 65                      90
sector 81                      90
sector 90                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 95                      57
sector 56                      57
sector 89                      56
sector 48                      56
sector 2                       55
sector 70a                     54
sector 43                      53
sector 70                      53
sector 37c                     53
sector 84                      51
sector-33 sohna road           51
sector 26                      50
sector 49                      48
sector 67                      48
sector 66                      46
sector 103                     45
sector 113                     43
sector 25                      43
sector 61                      42
sector 28                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 12                      30
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 112                     24
sector 57                      24
sector 24                      24
sector 88a                     23
sector 33                      23
sector 105                     23
sector 14                      23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 3                       20
sector 22                      20
sector 82a                     20
sector 78                      19
sector 47                      19
gwal pahari                    18
sector 63a                     18
sector 74                      18
sector 62                      17
sector 91                      17
sector 99                      16
sector 110                     16
sector 60                      15
sector 63                      15
sector 53                      14
sector 76                      14
sector 55                      14
sector 1 manesar               14
sector 52                      14
sector 46                      13
sector 36a                     13
sector 4 phase 2               13
sector 6                       13
sector 9                       13
sohna road road                12
sector 93                      12
sector 39                      12
sector 31                      12
sector 38                      12
sector 9a                      11
sector 41                      11
sector 3 phase 3 extension     11
sector 1a manesar              10
sector 13                      10
sector 95a                      9
sector 45                       9
sector 3 phase 2                9
manesar                         9
dwarka expressway               8
sector 8                        8
sector 23                       8
sector 2 extension              8
sector 17                       8
sector 40                       8
sector 10a                      8
sector 59                       8
sector 89 a                     8
c block sector 43               8
sector 58                       7
sector 36 sohna road            7
sector 51                       7
sector 1                        6
sector 21                       6
sector 5                        6
sector 80                       5
new sector 2                    5
saraswati vihar                 5
sector 23a                      5
sector 30                       5
sector 36                       4
new                             4
sector 3a                       4
sector 12a                      4
maruti kunj                     3
sector 17a                      3
sector 73                       3
a block sector 43               3
sector 88b                      3
sector 15                       3
sector 27                       3
sector 17b                      3
patel nagar                     3
b block sector 43               3
sector 110 a                    3
Name: count, dtype: int64

In [62]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [63]:

df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [64]:
df['sector']

0                        sector 79
1                        sector 60
2                        sector 89
3                        sector 12
4                        sector 72
5                        sector 70
6                        sector 61
7                        sector 25
8                       sector 108
9                        sector 13
10                       sector 90
11                       sector 71
12                 sohna road road
13                       sector 25
14                      sector 110
15                      sector 102
16                      sector 110
17                      sector 108
18                      sector 113
19                      sector 37c
20                       sector 81
21                       sector 54
22                      sector 103
23                       sector 90
24                       sector 92
25                       sector 26
26                       sector 61
27                      sector 102
28                       sector 25
29                       sector 47
30                        sector 2
31                      sector 112
32                       sector 92
33                       sector 86
34                       sector 82
35                       sector 77
36                      sector 102
37                       sector 72
38                       sector 83
39                       sector 46
40                      sector 102
41                      sohna road
42                       sector 33
43                      sector 102
44                       sector 25
46                       sector 99
47                       sector 86
48                       sector 14
49                       sector 83
50                      sohna road
51                      sector 113
52                       sector 89
53                       sector 28
54                       sector 70
55                       sector 84
56                       sector 58
57                      sector 99a
58                       sector 43
59                       sector 85
60                       sector 83
62                      sector 103
63                       sector 95
64                      sector 102
65                       sector 25
66                       sector 66
67                       sector 86
68                       sector 65
69                       sector 67
70                      sohna road
71                       sector 86
72                      sector 70a
73                       sector 33
74                      sector 88a
75                      sector 105
76                      sector 37d
77                      sector 37d
78                      sector 104
79                     gwal pahari
80                       sector 92
81                        sector 3
82                       sector 69
83                    new sector 2
84                       sector 33
85                       sector 33
86                      sohna road
87                      sector 108
88                       sector 70
89                      sohna road
90                       sector 49
91                       sector 33
92                       sector 25
93                        sector 2
94                      sohna road
95                       sector 24
96                       sector 54
97                       sector 74
98                       sector 86
99                        sector 2
100                      sector 69
101                      sector 28
102                      sector 50
103                     sector 102
104                     sector 113
105                      sector 86
106                      sector 92
107                     sector 109
108                     sector 37d
110                     sector 37d
111                      sector 41
112                      sector 81
113                      sector 99
114                      sector 93
115                     sector 110
116                      sector 65
117                      sector 91
118                      sector 89
119                     sector 102
120                      sector 26
121                       sector 2
122                      sector 79
123                     sector 67a
124                     sector 37c
125                     sector 82a
126                      sector 90
127                      sector 90
128                      sector 52
129                      sector 14
130                      sector 33
131                     sector 99a
132                      sector 26
133                      sector 47
134                     sector 107
135                      sector 79
136                      sector 26
137                      sector 52
138                      sector 92
139                      sector 12
140                      sector 43
141                      sector 85
142                      sector 43
143                      sector 79
144                      sector 82
145                     sector 67a
146                     sector 102
147                       sector 3
148                      sector 33
149                     sector 37c
150                     sector 109
151                     sector 37d
152                      sector 52
153              dwarka expressway
154                     sector 70a
155                      sector 79
156                      sector 85
157                     sector 103
158                      sector 33
159                      sector 83
160                      sector 85
161                       sector 2
162                       sector 6
164                      sector 22
165                     sector 63a
166                      sector 89
167                       sector 2
168                      sector 68
169                      sector 69
170                      sector 22
171                       sector 9
172                      sector 85
173                     sohna road
174                      sector 81
175                      sector 83
176                     sohna road
177                      sector 24
178                      sector 33
179                      sector 45
180                     sector 106
181                      sector 25
182                      sector 55
183                      sector 74
184                     sector 102
185                      sector 81
186                     sector 110
187                      sector 9a
188                      sector 48
189                     sohna road
190                     sohna road
191                      sector 84
192                       sector 3
193                     sector 82a
194                       sector 2
195                      sector 28
196                      sector 72
197                     sector 17a
198                     sector 67a
199                     sector 70a
200                      sector 67
201                     sector 104
202                      sector 56
203                      sector 89
204                      sector 26
205                      sector 66
206                     sector 108
207                      sector 69
208                     sector 88a
209                       sector 2
210                      sector 49
211                      sector 85
212                      sector 67
213                      sector 89
214                     sector 102
215                      sector 79
216                     sohna road
217                       sector 2
218                      sector 9a
219                      sector 73
220                     sector 103
221                     sohna road
222                      sector 72
223                      sector 92
224                     sector 108
225                      sector 56
226                      sector 70
227                     sector 107
228                       sector 2
229                      sector 56
230                      sector 69
231                      sector 33
232                      sector 78
233                      sector 74
234                      sector 38
235                       sector 7
236                      sector 26
237                      sector 81
238                     sector 36a
239               sector 3 phase 2
240                      sector 67
241                     sector 109
242                      sector 52
243                      sector 83
244                      sector 43
245                      sector 43
246                      sector 83
248                      sector 86
249                     sector 37d
250                     sector 109
251                      sector 83
252                      sector 89
253                      sector 85
254                     sohna road
255                     sector 103
256                      sector 72
257                       sector 9
258                      sector 28
259                     sector 102
260                       sector 4
261                     sector 67a
262                       sector 4
263                      sector 90
264                      sector 61
265                      sector 25
266                      sector 92
267                      sector 69
268                      sector 63
269                      sector 43
270                      sector 82
271                      sector 43
272                      sector 89
273               sector 3 phase 2
274                     sector 107
275                      sector 65
276                     sector 63a
277                     sohna road
278                      sector 67
279                     sohna road
280                      sector 65
281                     sohna road
282                      sector 25
283                      sector 61
284                      sector 26
285                     sector 107
286                     sector 112
287                      sector 31
288                      sector 14
289                      sector 92
290                       sector 4
291                      sector 12
292                      sector 13
293                      sector 66
294                      sector 85
295                      sector 95
296                      sector 62
297                      sector 22
298                     sector 10a
299                     sector 104
300                      sector 76
301                     sector 102
302                        manesar
303                      sector 92
304                      sector 90
306                      sector 25
309                      sector 79
310                       sector 7
311                     sector 107
312                      sector 43
314                      sector 26
315                      sector 86
316                      sector 40
317                      sector 85
318                      sector 86
319                      sector 24
320                      sector 65
321                      sector 85
322                     sector 108
323                      sector 79
324                     sector 88a
325                      sector 26
326                      sector 50
327                      sector 90
328                      sector 49
329                      sector 90
330                      sector 28
331                       sector 7
332                      sector 60
333                       sector 7
334                      sector 95
335                      sector 45
336                      sector 79
337                      sector 69
338                      sector 50
339                      sector 92
340                     sector 107
341                      sector 51
342                      sector 69
343                     sector 10a
344               sector 3 phase 2
345                      sector 48
346                      sector 84
347                      sector 47
348                      sector 51
349                     sohna road
350                     sector 105
351                     sector 104
352                     sector 104
353                      sector 59
354                      sector 83
355                      sector 81
356                      sector 60
357                     sector 109
358                      sector 83
359                      sector 48
360                      sector 25
361                      sector 70
362                     sector 109
363                      sector 57
364                      sector 68
365                     sector 109
366                     sector 102
367                     sector 113
368                     sohna road
369                      sector 31
370                      sector 90
371                       sector 2
372                      sector 89
373                     sector 104
374                sohna road road
375                     sector 109
376                      sector 92
377                     sector 37c
378                      sector 25
379                      sector 72
381                     sector 70a
382                      sector 11
383                      sector 65
384                      sector 54
385                     sector 102
386                      sector 77
387               sector 3 phase 2
388                      sector 69
389                      sector 84
390                      sector 77
391                      sector 90
392                      sector 50
393                      sector 67
394                      sector 77
395                      sector 73
396                      sector 25
397                      sector 92
398                     sector 63a
399                     sector 108
400                     sector 108
402                        manesar
403                sohna road road
404                     sector 108
405                      sector 86
406                     sector 113
407                      sector 41
408                      sector 81
409                      sector 67
410                            new
411                      sector 61
412                      sector 69
414                      sector 92
415                     sector 110
417                      sector 85
418                      sector 69
419                      sector 65
420                     sector 106
421                      sector 54
422                      sector 23
423                      sector 60
424                      sector 92
425                     sector 107
426                      sector 89
427                      sector 46
428                     sohna road
429                     sector 37c
430                      sector 86
431                      sector 70
432                      sector 65
433                      sector 92
434                     sector 104
435                     sohna road
436                      sector 92
437                      sector 95
438                      sector 69
439                      sector 52
440                     sector 99a
442                     sector 67a
443                      sector 82
444                      sector 70
445                      sector 82
446                      sector 76
447                     sector 109
448                     sector 113
449                     sector 37d
450                      sector 26
451                      sector 43
452                      sector 72
453                      sector 24
454                      sector 61
455     sector 3 phase 3 extension
456                     sector 102
457                    gwal pahari
458                      sector 79
459                     sector 70a
460                      sector 40
461                      sector 65
462                      sector 56
463                     sector 109
464                      sector 69
465                     sector 108
466                     sector 107
467                      sector 65
468                      sector 79
469                      sector 72
470                       sector 4
471                       sector 4
472                      sector 48
473                     sector 63a
474                       sector 3
475                     sohna road
476                      sector 57
477                      sector 47
478                      sector 48
479                      sector 14
480                     sector 37c
481                      sector 60
482                     sector 107
483                     sohna road
485                      sector 48
486                      sector 76
487                      sector 62
488                        manesar
489                      sector 61
490                     sector 108
491                      sector 95
492                      sector 85
493                      sector 50
494                     sector 108
495                      sector 86
496                       sector 4
497                      sector 85
498                     sector 109
500                       sector 2
501                      sector 83
502                      sector 81
503                     sector 88b
504                     sector 102
505                      sector 24
506                      sector 26
507                     sector 37d
508                      sector 86
509                      sector 72
510                     sector 108
511                     sector 105
512                      sector 85
513                      sector 81
514                      sector 51
515                      sector 92
516                     sector 107
517                      sector 65
519                     sector 103
520                      sector 69
521                     sector 99a
522                      sector 83
523                      sector 49
524                     sector 103
525                      sector 48
526                     sohna road
527                     sector 109
528                            new
529                      sector 84
530                     sohna road
531                sohna road road
532                      sector 95
533                      sector 81
534                     sector 37d
535                      sector 55
536                     sector 37d
538                      sector 63
539                      sector 12
541                       sector 4
542                       sector 2
543                     sector 113
544                      sector 90
545                      sector 69
546                     sector 88a
547                      sector 25
548                      sector 92
549                      sector 71
550                      sector 60
552                      sector 28
553                      sector 49
554                sohna road road
555                     sector 108
557                      sector 56
558                       sector 2
559                     sector 112
560                     sohna road
561                      sector 92
562                      sector 24
564                     sohna road
565                      sector 86
566               sector 3 phase 2
567                     sector 109
568                      sector 90
569                     sector 104
570                      sector 70
571                      sector 50
572                      sector 92
573                     sector 104
574                       sector 7
575                      sector 41
576                     sohna road
577                      sector 70
578                      sector 12
579                       sector 3
581                      sector 33
582                      sector 63
583                       sector 4
584                      sector 33
585                      sector 69
586                      sector 49
587                      sector 26
588                       sector 7
589                     sohna road
590                     sector 99a
591                     sector 107
592                      sector 66
593                      sector 67

In [67]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
410,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
528,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
2193,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2398,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN

In [69]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'

In [70]:

df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
83,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1390,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
1713,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
1924,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
3431,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [71]:
df.loc[[311,1072,1486,3040,3875],'sector'] = 'sector 110'

In [72]:
df.shape

(3803, 21)

In [73]:
df.duplicated().sum()

np.int64(0)

In [74]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 79 Gurgaon,flat,godrej,sector 79,1.93,8532.0,2262.0,Super Built up area 2262(210.15 sq.m.),3,4,3+,servant room,"Aa2, Sector 79 Gurgaon, Gurgaon, Haryana",5.0,East,1 to 5 Year Old,"['Vatika Town Square-INXT', 'Naurangpur Road',...","This 3 bhk flat is located in godrej 101, whic...",NaN,"['Centrally Air Conditioned', 'Security / Fire...","['Green Area5 out of 5', 'Construction5 out of..."
1,3 BHK Flat in Sector 60 Gurgaon,flat,ireo skyon,sector 60,3.00,12484.0,2403.0,Super Built up area 2403(223.25 sq.m.)Built Up...,3,3,3,servant room,"507, Sector 60 Gurgaon, Gurgaon, Haryana",5.0,North-East,1 to 5 Year Old,"['Sector 55-56 Metro', 'Golf Course Extension'...",Located in the popular residential address of ...,"['4 Wardrobe', '1 Water Purifier', '1 Exhaust ...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
2,2 BHK Flat in Sector 89 Gurgaon,flat,greenopolis,sector 89,0.65,5195.0,1251.0,Carpet area: 1251 (116.22 sq.m.),2,2,2,not available,"Sector 89 Gurgaon, Gurgaon, Haryana",15.0,NaN,Aug 2024,"['Orris Community Center', 'Indian Oil', 'Essa...",Greenopolis 2bhk on high floor in tower 5,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,4 Bedroom House for sale in Subhash Nagar,house,independent,sector 12,0.90,13333.0,675.0,Built Up area: 675 (62.71 sq.m.),4,4,0,not available,"Subhash Nagar, Sector 12a, Subhash Nagar, Gurg...",2.0,NaN,undefined,NaN,Best in class property available at subhash na...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment3.5 out of 5', 'Lifestyle4.5 out ..."
4,4 BHK Flat in Sector 72 Gurgaon,flat,tata primanti,sector 72,3.20,12190.0,2625.0,Super Built up area 2625(243.87 sq.m.)Built Up...,4,4,3+,servant room,"1302, Sector 72 Gurgaon, Gurgaon, Haryana",8.0,North,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...","Situated in sector 72 gurgaon, tata primanti i...","['6 Fan', '4 Geyser', '1 Stove', '12 Light', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."

In [76]:
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
2232,house,independent,sector 109,1.55,6567.0,2360.0,Built Up area: 2360 (219.25 sq.m.),3,2,0,not available,1.0,NaN,undefined,NaN,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN
114,flat,spaze privvy the address,sector 93,1.45,8033.0,1805.0,Super Built up area 1805(167.69 sq.m.)Built Up...,3,4,2,not available,12.0,North-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Hayatpur Road', 'Dwarka ...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
1026,flat,mapsko royale ville,sector 82,1.15,6424.0,1790.0,Super Built up area 1790(166.3 sq.m.),3,4,2,"servant room,pooja room",15.0,North-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Golf Course Ext Rd', ""St...","['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
2531,house,independent,sector 31,9.25,39530.0,2340.0,Plot area 265(221.57 sq.m.)Built Up area: 262 ...,12,12,3+,"pooja room,servant room,others",4.0,North-East,0 to 1 Year Old,"['Hanuman Mandir', 'Icici bank ATM', 'State ba...","['12 Wardrobe', '1 Exhaust Fan', '12 Geyser', ...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
1908,house,rattan garden,sector 7,1.30,13499.0,963.0,Built Up area: 963 (89.47 sq.m.),5,3,2,not available,3.0,NaN,10+ Year Old,"['Chintapurni Mandir', 'Aryan Hospital', 'D.R....","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN

In [77]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features

In [78]:
df.duplicated().sum()

np.int64(121)

In [79]:
df.to_csv('gurgaon_properties_cleaned_v1.csv', index=False)