In [68]:
import numpy as np 
import pandas as pd

In [69]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [70]:
df = pd.read_csv('flats.csv')

In [71]:
df.head(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,https://www.99acres.com/2-bhk-bedroom-apartmen...,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,https://www.99acres.com/2-bhk-bedroom-apartmen...,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [72]:
# shape 
df.shape

(3017, 20)

In [73]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3017 entries, 0 to 3016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3017 non-null   object
 1   link             3017 non-null   object
 2   society          3016 non-null   object
 3   price            3007 non-null   object
 4   area             3004 non-null   object
 5   areaWithType     3008 non-null   object
 6   bedRoom          3008 non-null   object
 7   bathroom         3008 non-null   object
 8   balcony          3008 non-null   object
 9   additionalRoom   1694 non-null   object
 10  address          3002 non-null   object
 11  floorNum         3006 non-null   object
 12  facing           2127 non-null   object
 13  agePossession    3007 non-null   object
 14  nearbyLocations  2913 non-null   object
 15  description      3008 non-null   object
 16  furnishDetails   2203 non-null   object
 17  features         2594 non-null   object
 18  rating           2676 non-null   object
 19  property_id      3008 non-null   object
dtypes: object(20)
memory usage: 471.5+ KB

In [74]:
df.duplicated().sum()

np.int64(0)

In [75]:
df.isnull().sum()

property_name         0
link                  0
society               1
price                10
area                 13
areaWithType          9
bedRoom               9
bathroom              9
balcony               9
additionalRoom     1323
address              15
floorNum             11
facing              890
agePossession        10
nearbyLocations     104
description           9
furnishDetails      814
features            423
rating              341
property_id           9
dtype: int64

In [76]:
df.drop(columns=['link','property_id'], inplace=True)

In [77]:
df.head(5)

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [78]:
# rename columns 
df.rename(columns={'area':'price_per_sqft'}, inplace=True)

In [79]:
df.head(10)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."
5,2 BHK Flat in Sector 36 Gurgaon,Signature Global Infinity Mall,41 Lac,"₹ 6,269/sq.ft.",Built Up area: 654 (60.76 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna Sector 36, Sector 36 Gurgaon, Gurgaon, H...",3rd of 3 Floors,NaN,undefined,NaN,Best in class property available at sector 36 ...,NaN,NaN,NaN
6,3 BHK Flat in Dwarka Expressway Gurgaon,The Cocoon,2 Crore,"₹ 13,333/sq.ft.",Super Built up area 1500(139.35 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Dwarka Expressway Gurgaon, Gurgaon, Haryana",5th of 25 Floors,NaN,0 to 1 Year Old,"['Shri Multispeciality Hospital', 'Esic Hospit...",Residential apartment for sell.The property co...,[],NaN,NaN
7,3 BHK Flat in Sector 104 Gurgaon,ATS Triumph3.9 ★,1.8 Crore,"₹ 7,860/sq.ft.",Carpet area: 2290 (212.75 sq.m.),3 Bedrooms,4 Bathrooms,3 Balconies,NaN,"Sector 104 Gurgaon, Gurgaon, Haryana",14th of 27 Floors,NaN,0 to 1 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...",Ats triumph is one of gurgaon's most sought af...,[],"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area4 out of 5', 'Amenities4.5 out of ..."
8,2 BHK Flat in Sector 88B Gurgaon,Vatika Xpressions,1.1 Crore,"₹ 8,148/sq.ft.",Built Up area: 1350 (125.42 sq.m.)Carpet area:...,2 Bedrooms,4 Bathrooms,3+ Balconies,Study Room,"H 23, Sector 88B Gurgaon, Gurgaon, Haryana",2nd of 3 Floors,North-East,Under Construction,"['Dwarka Expressway', 'Adarsh public school,Ga...",We are the proud owners of this 2 bhk apartmen...,NaN,"['Feng Shui / Vaastu Compliant', 'Intercom Fac...",NaN
9,3 BHK Flat in Sector 78 Gurgaon,Raheja Revanta,4.75 Crore,"₹ 16,885/sq.ft.",Built Up area: 2813 (261.34 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,Servant Room,"Sector 78 Gurgaon, Gurgaon, Haryana",31st of 40 Floors,NaN,Dec 2023,"['Sapphire 83 Mall', 'NH-8', 'Bal Bharti Publi...","This 3 bhk flat is located in raheja revanta, ...",NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [80]:
df['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Smart World Gems                                     32
Emaar MGF Emerald Floors Premier3.8 ★                32
Smart World Orchard                                  32
DLF The Ultima4.0 ★                                  31
Paras Dews                                           31
DLF Regal Gardens3.9 ★                               30
Shree Vardhman Flora3.8 ★                            29
M3M Woodshire4.0 ★                                   29
La Vida by Tata Housing                              28
Signature Global Solera3.7 ★                         28
Godrej Nature Plus                                   27
Emaar Gurgaon Greens4.1 ★                            25
BPTP Terra3.8 ★                                      25
Experion The Heartsong3.9 ★                          24
Eldeco Accolade3.8 ★                                 24
Vatika Gurgaon 213.7 ★                               24
DLF New Town Heights 13.9 ★                          24
Bestech Park View Residency3.9 ★                     23
M3M Heights                                          22
Tata Primanti4.1 ★                                   22
ATS Triumph3.9 ★                                     22
Emaar Palm Gardens4.1 ★                              22
ROF Ananda                                           21
Sare Crescent Parc3.5 ★                              21
Godrej 1014.0 ★                                      20
Experion Windchants3.8 ★                             20
Sare Homes                                           19
Antriksh Heights3.7 ★                                19
Ambience Creacions                                   18
ATS Tourmaline3.9 ★                                  18
Indiabulls Centrum Park3.7 ★                         18
Mapsko Mount Ville4.1 ★                              18
Supertech Araville                                   18
CHD Avenue 713.6 ★                                   18
Sobha City                                           18
M3M Golfestate4.4 ★                                  17
Conscient Heritage Max4.3 ★                          17
GLS Arawali Homes3.8 ★                               17
Godrej Summit3.7 ★                                   17
Pareena Coban Residences                             17
M3M Skywalk                                          17
Bestech Park View Grand Spa4.3 ★                     16
M3M Merlin3.7 ★                                      16
HCBS Sports Ville3.6 ★                               16
Umang Monsoon Breeze                                 15
Emaar MGF The Palm Drive4.1 ★                        15
Ansal Heights 86                                     15
Godrej Oasis3.9 ★                                    15
Umang Winter Hills3.9 ★                              14
Ramsons Kshitij3.7 ★                                 14
DLF The Primus3.9 ★                                  14
Orchid Petals4.1 ★                                   14
The Close North4.0 ★                                 14
Ireo Skyon4.0 ★                                      14
Vatika The Seven Lamps3.8 ★                          14
Ireo Victory Valley4.1 ★                             14
Indiabulls Enigma                                    14
Corona Optus3.9 ★                                    14
Imperia The Esfera                                   14
MVN Athens3.7 ★                                      14
Ireo The Corridors                                   13
Bestech Park View Ananda4.2 ★                        13
Puri Emerald Bay3.7 ★                                13
Central Park Flower Valley                           13
M3M Soulitude                                        11
DLF The Skycourt4.2 ★                                11
Godrej Aria3.8 ★                                     11
TARC Maceo3.8 ★                                      11
SBTL Caladium                                        11
Breez Global Hill View                               11
Adani M2K Oyster Grande3.9 ★                         11
Alpha Corp GurgaonOne 844.0 ★                        11
Raheja Vedaanta3.6 ★                                 11
Puri Diplomatic Greens4.0 ★                          10
Capital Residences 360                               10
ATS Kocoon                                           10
Ramprastha The Edge Towers3.5 ★                      10
Signature Global Synera3.4 ★                         10
DLF New Town Heights 24.0 ★                          10
Breez Global Heights4.2 ★                            10
Emaar MGF Palm Hills4.0 ★                            10
Zara Aavaas                                          10
Pyramid Urban Homes 2                                10
Godrej Air                                           10
Pivotal Devaan                                       10
Parsvnath Green Ville3.9 ★                            9
Bestech Park View Sanskruti4.2 ★                      9
AIPL The Peaceful Homes3.9 ★                          9
Pareena Mi Casa                                       9
Microtek Greenburg3.8 ★                               9
ILD Greens4.1 ★                                       9
Vatika City4.1 ★                                      9
Tulip Ivory3.5 ★                                      8
GLS Avenue 51                                         8
ss                                                    8
Bestech Altura                                        8
AVL 36 Gurgaon3.7 ★                                   8
Orris Aster Court Premier                             8
The Lions CGHS                                        8
Emaar Digihomes                                       8
M3M Capital                                           8
Birla Navya                                           8
Assotech Blith                                        8
Vatika Lifestyle Homes3.8 ★                           8
M3M Skycity                                           8
Signature Andour Heights3.8 ★                         7
Emaar Imperial Gardens3.8 ★                           7
Signature Global Orchard Avenue3.6 ★                  7
Sare Crescent Parc Royal Greens Phase 1               7
Mapsko Casa Bella3.8 ★                                7
Vipul Lavanya3.9 ★                                    7
Ireo The Grand Arch4.0 ★                              7
Signature Global City                                 7
Sare Green ParC Phase 3                               7
Ansal Housing Highland Park                           7
Orris Carnation Residency3.7 ★                        7
Trisara Our Homes 3                                   7
AIPL Zen Residences                                   7
DLF Regency Park 13.6 ★                               6
HSIIDC Sidco Aravali                                  6
Bestech Park View City4.1 ★                           6
Signature Global Park 4                               6
Suncity Vatsal Valley                                 6
Mapsko Royale Ville3.7 ★                              6
Sidhartha NCR One Phase 14.2 ★                        6
Greenopolis                                           6
Hero Homes                                            6
Signature Global City 63A                             6
Signature The Roselia3.6 ★                            6
Pyramid Urban                                         6
Shapoorji Pallonji Joyville Gurugram                  6
Supertech Hues                                        6
Ashiana Mulberry                                      6
BPTP Astaire Gardens3.7 ★                             6
Pioneer Araya3.8 ★                                    6
Bestech Park View Spa Next4.0 ★                       6
Parsvnath Exotica3.7 ★                                6
M3M Sierra 68                                         6
Kiran Residency                                       6
Ireo Uptown4.1 ★                                      5
Silverglades The Melia                                5
Signature Global Grand IVA3.9 ★                       5
Conscient Elevate                                     5
Godrej Habitat                                        5
Essel Towers                                          5
Vatika Sovereign Park                                 5
ATS Marigold                                          5
Adani Brahma Samsara Vilasa                           5
Signature Global City 37D Ph 2                        5
Krisumi Waterfall Residences                          5
Central Park Flower Valley Aqua Front Towers          5
Ashiana Anmol3.5 ★                                    5
Green Court3.7 ★                                      5
Vatika City Homes3.9 ★                                5
DLF Park Place4.1 ★                                   5
Pareena Laxmi Apartments3.6 ★                         5
Satya The Hermitage3.5 ★                              5
Emaar MGF Emerald Estate3.8 ★                         5
Pioneer Park3.8 ★                                     5
Signature Global City 92                              5
Signature Global the Millennia                        5
DLF Regency Park 24.0 ★                               5
Central Park Resorts4.4 ★                             5
Tulip Monsella                                        5
M3M The Marina4.0 ★                                   5
Signature Global City 81                              5
Apna Enclave                                          5
Unitech Vistas                                        4
Global Hill View                                      4
Railway Officers RPF Society                          4
Corona Gracieux                                       4
ILD Grand                                             4
Sare Petioles                                         4
Raheja Navodaya3.6 ★                                  4
Ramprastha Primera                                    4
Unitech Fresco3.8 ★                                   4
Signature The Serenas                                 4
Godrej Frontier3.7 ★                                  4
Prime Habitat                                         4
Tata Gurgaon Gateway3.8 ★                             4
Ramprastha Skyz                                       4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
DLF New Town Heights3.7 ★                             4
SS The Coralwood3.4 ★                                 4
Lotus Homz4.0 ★                                       4
DLF The Skycourt                                      4
Orris Aster Court                                     4
Godrej Icon                                           4
Emaar Palm Heights                                    4
Krrish Provence Estate                                4
Spaze Privvy The Address3.9 ★                         3
DLF The Arbour                                        3
Sare Green Parc 2                                     3
DLF Express Greens3.9 ★                               3
Ambience Lagoon3.9 ★                                  3
Unitech Heritage City                                 3
The Roselia 2                                         3
Valley View Estate                                    3
Sare Green Parc                                       3
Vatika Independent Floors3.8 ★                        3
Kendriya Vihar4.1 ★                                   3
Piedmont Taksila heights3.6 ★                         3
DLF The Grove                                         3
Tulip Petals3.6 ★                                     3
Shri Ram Apartments                                   3
Unitech Uniworld Gardens3.8 ★                         3
Tulip White3.5 ★                                      3
Smriti Apartment                                      3
Sapphire Eighty Three                                 3
DLF Royalton Tower                                    3
DLF Carlton Estate4.0 ★                               3
Sukhshanti Apartment                                  3
SS Almeria                                            3
DLF Belvedere Towers3.8 ★                             3
Satya Element One                                     3
AIPL Club Residences                                  3
Vatika Xpressions                                     3
Raheja Revanta                                        3
My Home                                               3
Brisk Lumbini Terrace Homes                           3
Deepak Minda                                          3
Maxworth City Residences                              3
Apex Our Homes                                        3
Shri Banke Bihari Society3.8 ★                        3
AFNHB Jalvayu Vihar3.7 ★                              3
Spaze Privy AT43.9 ★                                  3
ATS Kocoon4.2 ★                                       3
Dhoot Time Residency4.0 ★                             3
Sidhartha NCR One                                     3
Raheja Sampada                                        3
Sunischit Apartments                                  3
Bestech Park View City 23.9 ★                         3
Pyramid Elite                                         3
Suncity Platinum Towers                               3
Mahindra Aura4.2 ★                                    3
Shree Arihant Apartment                               3
Guru Gram Haryana CGHS4.1 ★                           3
Siddhartha Apartment                                  3
Pivotal Riddhi Siddhi                                 3
Adani Aangan Arcade                                   3
Whiteland Blissville                                  3
Signature Global Solera 2                             3
Tulip Purple                                          3
Chintels Paradiso3.9 ★                                3
Essel Tower                                           3
Unitech Sunbreeze                                     3
Raheja Atharva3.6 ★                                   3
Krrish Florence Estate                                3
Sidhartha NCR Greens4.3 ★                             3
Paras Quartier                                        3
Spaze Privy3.9 ★                                      3
Unitech The Residences3.7 ★                           3
Tulip Lemon3.9 ★                                      3
Puri Diplomatic Greens3.9 ★                           3
Conscient Habitat3.6 ★                                3
Today Callidora                                       2
Landmark The Residency                                2
Ramprastha The Atrium3.4 ★                            2
Samaspurkunj                                          2
Mahindra Luminare4.0 ★                                2
Maruti Vihar                                          2
Vipul World Floors                                    2
Unitech Uniworld Gardens 23.4 ★                       2
Apartment                                             2
Lavanya Apartments                                    2
Park Royal Apartment                                  2
Vasant Appartments                                    2
Surendra Avenue 69                                    2
MRG World Ultimus                                     2
BPTP Pedestal                                         2
Mapsko Paradise3.9 ★                                  2
Jammu and Kashmir Bank Employees CGHS3.7 ★            2
Sidhivinayak Apartments                               2
Bhagwati Sadan                                        2
Ambience Caitriona                                    2
Breeze Global Heights                                 2
Silverglades Hightown Residences                      2
Dlf City                                              2
Shapoorji Pallonji Joyville                           2
Milan CGHS 9                                          2
Element One Service                                   2
om appartments                                        2
Ansal Heights3.2 ★                                    2
Suposhaa Smartworld Orchard                           2
Mittal Surya Vihar                                    2
Residency Grand                                       2
M3M Sky Lofts                                         2
Supertech Hilltown                                    2
Bestech Spa Signature                                 2
M3M Latitude                                          2
Vatika INXT Floors                                    2
Palam Vihar Society                                   2
Raheja Vanya                                          2
Housing Board Colony                                  2
HCBS Sports Ville                                     2
Adani Aangan Galleria                                 2
Tulip Orange3.9 ★                                     2
Central Park 2 Bellevue                               2
M3M Urbana                                            2
NBCC Heights3.9 ★                                     2
Supertech Hill Town                                   2
Suncity Avenue 76                                     2
Ashiana Anmol                                         2
Godrej Nature Plus Serenity                           2
The Close South3.9 ★                                  2
Ganga Apartment                                       2
Suncity Heights3.7 ★                                  2
lagoon apartment                                      2
Elan The Presidential                                 2
Oriental Valley CHS                                   2
Aqua Front Towers                                     2
Sahara Grace                                          2
CGHS Airport Apartment                                2
Ansal API Celebrity Suites                            2
Pioneer Urban Presidia                                2
ROF Aalayas3.8 ★                                      2
AWHO Shanti Vihar4.0 ★                                2
Ansal API Esencia3.7 ★                                2
Raheja Atlantis3.8 ★                                  2
Emaar MGF The Enclave                                 2
Ramprastha City                                       2
Vipul Belmonte3.9 ★                                   2
BPTP Amstoria3.8 ★                                    2
The Penthouses at the Hibiscus                        2
M3M Ikonic                                            2
Vatika Emilia Floors3.7 ★                             2
Ardee City3.8 ★                                       2
Tulip Violet                                          2
Tulip Leaf                                            2
Viridian The Plaza 106                                2
Signature Global The Millennia 3                      2
Emaar MGF Palm Studios                                2
Orchid Island4.2 ★                                    2
Green Campus CHS                                      2
DLF The Crest3.6 ★                                    2
Bestech Park View Sanskruti4.1 ★                      2
Professors Enclave CGHS                               2
DLF The Icon3.7 ★                                     2
SS Hibiscus                                           2
BPTP Mansions Park Prime                              2
DLF The Belaire3.9 ★                                  2
Suncity Avenue 1023.9 ★                               2
Puri The Aravallis                                    2
Paras Irene3.7 ★                                      2
BPTP Freedom Park Life4.0 ★                           2
Tulsiani Easy in Homes                                2
The Center Court                                      1
Uphaar Residency 2                                    1
Wings Apartment                                       1
Sidhartha NCR One Phase 24.1 ★                        1
Bestech Park View Ananda                              1

In [81]:
df['society'].value_counts().shape

(638,)

In [82]:
import re  # imports Python's regurlar Expression(Regex) library used for searching matching and replacing text patterns 
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()
# here .apply(lambda name: means runs the function on every line in the society columns 
# str(name) means converts the value to a string 
# re.sub(....) -- find the patterns and replace with something else

In [83]:
df.head(2)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [84]:
df['society'].value_counts().shape

(604,)

In [85]:
df['society'].value_counts()

society
tulip violet                                     75
ss the leaf                                      74
shapoorji pallonji joyville gurugram             45
dlf new town heights                             38
signature global park                            36
shree vardhman victoria                          35
emaar mgf emerald floors premier                 32
smart world gems                                 32
smart world orchard                              32
paras dews                                       31
dlf the ultima                                   31
dlf regal gardens                                30
m3m woodshire                                    30
shree vardhman flora                             29
signature global solera                          28
la vida by tata housing                          28
godrej nature plus                               27
bptp terra                                       25
emaar gurgaon greens                             25
vatika gurgaon                                   24
experion the heartsong                           24
eldeco accolade                                  24
bestech park view residency                      23
m3m heights                                      22
emaar palm gardens                               22
ats triumph                                      22
tata primanti                                    22
rof ananda                                       21
sare crescent parc                               21
godrej                                           21
experion windchants                              20
antriksh heights                                 19
sare homes                                       19
mapsko mount ville                               18
indiabulls centrum park                          18
ambience creacions                               18
m3m golfestate                                   18
chd avenue                                       18
ats tourmaline                                   18
m3m skywalk                                      18
hcbs sports ville                                18
sobha city                                       18
supertech araville                               18
godrej summit                                    17
pareena coban residences                         17
conscient heritage max                           17
gls arawali homes                                17
m3m merlin                                       16
bestech park view grand spa                      16
umang monsoon breeze                             15
ramsons kshitij                                  15
godrej oasis                                     15
dlf the skycourt                                 15
ansal heights 86                                 15
emaar mgf the palm drive                         15
corona optus                                     14
ireo victory valley                              14
the close north                                  14
imperia the esfera                               14
vatika the seven lamps                           14
dlf the primus                                   14
ireo skyon                                       14
bestech park view ananda                         14
orchid petals                                    14
mvn athens                                       14
umang winter hills                               14
indiabulls enigma                                14
central park flower valley                       13
ireo the corridors                               13
puri diplomatic greens                           13
puri emerald bay                                 13
ats kocoon                                       13
alpha corp gurgaonone                            11
bestech park view sanskruti                      11
breez global hill view                           11
tarc maceo                                       11
sbtl caladium                                    11
adani m2k oyster grande                          11
dlf regency park                                 11
m3m soulitude                                    11
raheja vedaanta                                  11
breez global heights                             11
godrej aria                                      11
emaar mgf palm hills                             10
pyramid urban homes 2                            10
ild greens                                       10
pivotal devaan                                   10
godrej air                                       10
ramprastha the edge towers                       10
zara aavaas                                      10
signature global synera                          10
capital residences 360                           10
aipl the peaceful homes                           9
parsvnath green ville                             9
vatika city                                       9
microtek greenburg                                9
pareena mi casa                                   9
bestech park view city                            9
avl 36 gurgaon                                    8
m3m capital                                       8
the lions cghs                                    8
birla navya                                       8
bestech altura                                    8
orris aster court premier                         8
emaar digihomes                                   8
ss                                                8
assotech blith                                    8
gls avenue 51                                     8
tulip ivory                                       8
vatika lifestyle homes                            8
m3m skycity                                       8
ansal housing highland park                       7
signature global orchard avenue                   7
ireo the grand arch                               7
sidhartha ncr one phase                           7
signature andour heights                          7
aipl zen residences                               7
orris carnation residency                         7
mapsko casa bella                                 7
sare crescent parc royal greens phase 1           7
signature global city                             7
emaar imperial gardens                            7
sare green parc phase 3                           7
vipul lavanya                                     7
trisara our homes 3                               7
ashiana anmol                                     7
bptp astaire gardens                              6
pyramid urban                                     6
supertech hues                                    6
signature the roselia                             6
green court                                       6
hero homes                                        6
parsvnath exotica                                 6
bestech park view spa next                        6
greenopolis                                       6
kiran residency                                   6
pioneer araya                                     6
m3m sierra 68                                     6
ashiana mulberry                                  6
mapsko royale ville                               6
suncity vatsal valley                             6
signature global park 4                           6
hsiidc sidco aravali                              6
signature global city 63a                         6
central park flower valley aqua front towers      5
signature global grand iva                        5
godrej habitat                                    5
signature global city 81                          5
unitech fresco                                    5
vatika sovereign park                             5
conscient elevate                                 5
ats marigold                                      5
tulip monsella                                    5
adani brahma samsara vilasa                       5
signature global city 37d ph 2                    5
pareena laxmi apartments                          5
satya the hermitage                               5
signature global the millennia                    5
m3m the marina                                    5
pioneer park                                      5
krisumi waterfall residences                      5
emaar mgf emerald estate                          5
central park resorts                              5
silverglades the melia                            5
signature global city 92                          5
unitech uniworld gardens                          5
essel towers                                      5
dlf park place                                    5
ireo uptown                                       5
vatika city homes                                 5
apna enclave                                      5
ild grand                                         4
raheja navodaya                                   4
ramprastha skyz                                   4
unitech vistas                                    4
signature the serenas                             4
railway officers rpf society                      4
afnhb jalvayu vihar                               4
lotus homz                                        4
dlf the arbour                                    4
hsiidc sidco shivalik apartments                  4
ramprastha primera                                4
godrej icon                                       4
krrish provence estate                            4
global hill view                                  4
kendriya vihar                                    4
essel tower                                       4
sare petioles                                     4
corona gracieux                                   4
emaar palm heights                                4
ss the coralwood                                  4
prime habitat                                     4
orris aster court                                 4
godrej frontier                                   4
tata gurgaon gateway                              4
unitech sunbreeze                                 3
brisk lumbini terrace homes                       3
smriti apartment                                  3
dlf carlton estate                                3
pivotal riddhi siddhi                             3
sidhartha ncr one                                 3
raheja sampada                                    3
pyramid elite                                     3
signature global solera 2                         3
my home                                           3
tulip petals                                      3
sare green parc 2                                 3
dlf express greens                                3
spaze privvy the address                          3
shri ram apartments                               3
spaze privy                                       3
raheja revanta                                    3
tulip lemon                                       3
conscient habitat                                 3
guru gram haryana cghs                            3
dhoot time residency                              3
sunischit apartments                              3
vatika xpressions                                 3
mahindra aura                                     3
bhagwati sadan                                    3
valley view estate                                3
siddhartha apartment                              3
dlf royalton tower                                3
the roselia 2                                     3
satya element one                                 3
apex our homes                                    3
spaze privy at                                    3
suncity platinum towers                           3
vatika independent floors                         3
shri banke bihari society                         3
whiteland blissville                              3
aipl club residences                              3
maxworth city residences                          3
dlf belvedere towers                              3
paras quartier                                    3
unitech the residences                            3
ambience lagoon                                   3
raheja atharva                                    3
krrish florence estate                            3
piedmont taksila heights                          3
sidhartha ncr greens                              3
deepak minda                                      3
unitech heritage city                             3
sapphire eighty three                             3
sukhshanti apartment                              3
tulip white                                       3
tulip purple                                      3
chintels paradiso                                 3
adani aangan arcade                               3
sare green parc                                   3
shree arihant apartment                           3
ss almeria                                        3
dlf the grove                                     3
puri the aravallis                                2
aqua front towers                                 2
today callidora                                   2
park royal apartment                              2
sahara grace                                      2
housing board colony                              2
bptp pedestal                                     2
mrg world ultimus                                 2
mapsko paradise                                   2
professors enclave cghs                           2
breeze global heights                             2
dlf city                                          2
ramprastha the atrium                             2
shapoorji pallonji joyville                       2
dlf the icon                                      2
element one service                               2
silverglades hightown residences                  2
nbcc heights                                      2
suncity heights                                   2
ambience caitriona                                2
surendra avenue 69                                2
jammu and kashmir bank employees cghs             2
sidhivinayak apartments                           2
oriental valley chs                               2
emaar mgf emerald floors                          2
maruti vihar                                      2
raheja atlantis                                   2
central park 2 bellevue                           2
tulip orange                                      2
adani aangan galleria                             2
milan cghs 9                                      2
ansal api celebrity suites                        2
cghs airport apartment                            2
ansal heights                                     2
m3m urbana                                        2
vatika inxt floors                                2
palam vihar society                               2
m3m latitude                                      2
pioneer urban presidia                            2
elan the presidential                             2
lagoon apartment                                  2
rof aalayas                                       2
signature global the millennia 3                  2
m3m sky lofts                                     2
vasant appartments                                2
shree shyam residency                             2
shyam apartment                                   2
ansal api esencia                                 2
mahindra luminare                                 2
bptp freedom park life                            2
the close south                                   2
landmark the residency                            2
awho shanti vihar                                 2
raheja vanya                                      2
godrej nature plus serenity                       2
suncity avenue 76                                 2
supertech hill town                               2
vipul world floors                                2
viridian the plaza 106                            2
ss hibiscus                                       2
the penthouses at the hibiscus                    2
bestech spa signature                             2
emaar mgf palm studios                            2
vatika emilia floors                              2
tulip leaf                                        2
ardee city                                        2
residency grand                                   2
ss residency                                      2
om appartments                                    2
suposhaa smartworld orchard                       2
mittal surya vihar                                2
supertech hilltown                                2
ganga apartment                                   2
apartment                                         2
lavanya apartments                                2
samaspurkunj                                      2
ramprastha city                                   2
orchid island                                     2
dlf the crest                                     2
green campus chs                                  2
suncity avenue                                    2
dlf the belaire                                   2
paras irene                                       2
bptp amstoria                                     2
m3m ikonic                                        2
vipul belmonte                                    2
emaar mgf the enclave                             2
bptp mansions park prime                          2
tulsiani easy in homes                            2
spire woods now ananda by alpha corp              1
maa bhagwati residency                            1
parkwood westend                                  1
signature global infinity mall                    1
the cocoon                                        1
divya apartments                                  1
ansals highland park                              1
ild grand centra                                  1
sobha smriti apartments                           1
conscient one                                     1
emaar palm premier                                1
lig flat                                          1
aditya apartment                                  1
ramprasta awho                                    1
maple heights                                     1
ikon tower baani city centre                      1
mittal cosmos executive apartments                1
ansal harmony homes                               1
shree balaji appartment                           1
ashok vihar phase 2                               1
central park flower valley cerise floors          1
lord krishna                                      1
unitech harmony                                   1
.                                                 1
emaar mgf palm terraces select                    1
hector trimurti heights                           1
unitech uniworld city                             1
bhawna cghs                                       1
ompee k s residency                               1
apex builders                                     1
central park resort belgravia residences          1
the serenas                                       1
the new people apartments                         1
chanderlok society                                1
ansal estella                                     1
laxmi apartment sector 99a gurgaon                1
sanskriti apartments                              1
millenia                                          1
emaar emerald hills                               1
ansal maple heights                               1
the nav manesar apartment                         1
signature global orchard avenue 2                 1

In [86]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [87]:
# Let's work upon the price column 
df['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.2 Crore           59
1.5 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.9 Crore           40
1.55 Crore          40
75 Lac              38
1.65 Crore          38
1.7 Crore           37
1.8 Crore           37
80 Lac              36
2.2 Crore           34
1.15 Crore          33
50 Lac              33
85 Lac              31
1.45 Crore          31
1.05 Crore          30
60 Lac              29
40 Lac              29
2.5 Crore           29
2.1 Crore           26
45 Lac              26
65 Lac              25
35 Lac              23
1.85 Crore          23
2.35 Crore          23
3 Crore             22
70 Lac              21
2.25 Crore          20
55 Lac              20
3.5 Crore           19
2.3 Crore           18
2.4 Crore           18
30 Lac              17
2.65 Crore          16
2.6 Crore           15
1.38 Crore          15
2.45 Crore          14
3.4 Crore           14
2.15 Crore          14
82 Lac              13
3.25 Crore          13
92 Lac              13
38 Lac              13
78 Lac              13
2.7 Crore           13
1.32 Crore          13
5 Crore             12
42 Lac              12
1.95 Crore          12
1.42 Crore          12
2.8 Crore           12
25 Lac              11
88 Lac              11
Price on Request    11
32 Lac              11
1.08 Crore          11
1.28 Crore          10
26 Lac              10
87 Lac              10
1.78 Crore          10
1.12 Crore          10
2.55 Crore          10
28 Lac              10
2.85 Crore           9
1.72 Crore           9
1.68 Crore           9
3.45 Crore           9
4 Crore              9
2.05 Crore           9
99 Lac               9
36 Lac               9
22 Lac               9
48 Lac               8
20 Lac               8
2.75 Crore           8
4.25 Crore           8
86 Lac               8
27 Lac               8
1.26 Crore           8
6.5 Crore            8
1.54 Crore           8
1.18 Crore           8
1.76 Crore           8
3.2 Crore            8
6 Crore              8
98 Lac               8
56 Lac               8
39 Lac               7
2.9 Crore            7
72 Lac               7
97 Lac               7
1.27 Crore           7
46 Lac               7
1.36 Crore           7
3.7 Crore            7
1.99 Crore           7
1.19 Crore           7
1.02 Crore           7
1.29 Crore           7
3.3 Crore            7
79 Lac               7
1.16 Crore           6
2.95 Crore           6
1.14 Crore           6
96 Lac               6
3.05 Crore           6
1.51 Crore           6
1.34 Crore           6
1.13 Crore           6
71.5 Lac             6
1.07 Crore           6
5.5 Crore            6
1.59 Crore           6
1.98 Crore           6
21 Lac               6
54 Lac               6
1.01 Crore           6
43 Lac               6
37 Lac               6
3.35 Crore           6
4.1 Crore            6
1.49 Crore           6
1.39 Crore           6
3.65 Crore           6
3.9 Crore            6
1.24 Crore           5
6.75 Crore           5
1.33 Crore           5
29 Lac               5
1.47 Crore           5
2.22 Crore           5
1.69 Crore           5
64 Lac               5
1.91 Crore           5
4.5 Crore            5
3.75 Crore           5
1.43 Crore           5
1.82 Crore           5
1.83 Crore           5
49 Lac               5
1.92 Crore           5
66 Lac               5
24 Lac               5
1.93 Crore           5
68 Lac               5
1.62 Crore           5
1.79 Crore           5
2.29 Crore           5
93 Lac               5
2.78 Crore           5
2.12 Crore           5
1.44 Crore           5
1.17 Crore           5
1.23 Crore           4
58 Lac               4
41.5 Lac             4
1.22 Crore           4
1.48 Crore           4
1.71 Crore           4
6.15 Crore           4
7 Crore              4
4.85 Crore           4
4.3 Crore            4
1.66 Crore           4
31 Lac               4
3.1 Crore            4
67 Lac               4
36.5 Lac             4
33 Lac               4
73 Lac               4
89 Lac               4
28.5 Lac             4
1.58 Crore           4
5.9 Crore            4
5.6 Crore            4
2.09 Crore           4
1.31 Crore           4
74 Lac               4
1.37 Crore           4
1.52 Crore           4
5.25 Crore           4
1.73 Crore           4
62 Lac               4
3.6 Crore            4
1.77 Crore           4
1.64 Crore           4
3.95 Crore           4
4.75 Crore           3
3.8 Crore            3
1.04 Crore           3
2.28 Crore           3
2.03 Crore           3
1.09 Crore           3
2.08 Crore           3
1.67 Crore           3
1.57 Crore           3
2.36 Crore           3
91 Lac               3
4.8 Crore            3
2.51 Crore           3
3.15 Crore           3
2.24 Crore           3
52 Lac               3
69 Lac               3
83 Lac               3
1.21 Crore           3
2.01 Crore           3
94 Lac               3
72.5 Lac             3
5.8 Crore            3
1.63 Crore           3
3.85 Crore           3
1.41 Crore           3
84 Lac               3
34 Lac               3
2.33 Crore           3
51 Lac               3
2.79 Crore           3
1.88 Crore           3
64.5 Lac             3
3.49 Crore           3
4.2 Crore            3
47 Lac               3
56.2 Lac             2
3.55 Crore           2
7.5 Crore            2
27.1 Lac             2
11 Crore             2
4.55 Crore           2
2.87 Crore           2
2.26 Crore           2
87.5 Lac             2
52.56 Lac            2
2.14 Crore           2
2.99 Crore           2
1.56 Crore           2
2.58 Crore           2
2.57 Crore           2
5.2 Crore            2
5.7 Crore            2
2.13 Crore           2
1.46 Crore           2
8 Crore              2
8.5 Crore            2
2.17 Crore           2
59 Lac               2
3.29 Crore           2
71 Lac               2
6.2 Crore            2
2.23 Crore           2
53.5 Lac             2
2.52 Crore           2
4.49 Crore           2
2.04 Crore           2
27.75 Lac            2
4.7 Crore            2
88.5 Lac             2
2.41 Crore           2
2.02 Crore           2
4.26 Crore           2
3.32 Crore           2
4.6 Crore            2
3.21 Crore           2
25.5 Lac             2
14 Crore             2
4.45 Crore           2
98.5 Lac             2
1.87 Crore           2
2.91 Crore           2
53 Lac               2
31.5 Lac             2
77.5 Lac             2
41 Lac               2
3.19 Crore           1
5.31 Crore           1
4.95 Crore           1
4.02 Crore           1
97.04 Lac            1
37.5 Lac             1
68.85 Lac            1
98.88 Lac            1
2.69 Crore           1
2.54 Crore           1
54.8 Lac             1
3.98 Crore           1
94.5 Lac             1
2.44 Crore           1
82.5 Lac             1
61 Lac               1
29.8 Lac             1
6.02 Crore           1
7.9 Crore            1
3.23 Crore           1
15 Crore             1
7.8 Crore            1
1.97 Crore           1
39.5 Lac             1
11.25 Crore          1
7.15 Crore           1
2.82 Crore           1
54.99 Lac            1
6.44 Crore           1
1.11 Crore           1
8.25 Crore           1
31.75 Lac            1
55.6 Lac             1
98.1 Lac             1
2.63 Crore           1
55.5 Lac             1
5.4 Crore            1
3.39 Crore           1
95.75 Lac            1
3.46 Crore           1
3.63 Crore           1
4.67 Crore           1
2.37 Crore           1
4.4 Crore            1
66.99 Lac            1
6.3 Crore            1
23 Lac               1
5.49 Crore           1
2.98 Crore           1
4.63 Crore           1
2.34 Crore           1
6.16 Crore           1
5.3 Crore            1
2.72 Crore           1
4.78 Crore           1
2.21 Crore           1
2.48 Crore           1
89.5 Lac             1
99.5 Lac             1
3.83 Crore           1
3.79 Crore           1
3.67 Crore           1
71.2 Lac             1
27.5 Lac             1
23.5 Lac             1
4.79 Crore           1
6.25 Crore           1
35.5 Lac             1
2.11 Crore           1
1.06 Crore           1
4.94 Crore           1
10.75 Crore          1
81 Lac               1
26.1 Lac             1
9.14 Crore           1
8.35 Crore           1
20.5 Lac             1
17.5 Lac             1
24.5 Lac             1
10 Crore             1
6.1 Crore            1
5.75 Crore           1
2.77 Crore           1
7.56 Crore           1
79.9 Lac             1
68.5 Lac             1
85.5 Lac             1
93.75 Lac            1
94.25 Lac            1
80.5 Lac             1
2.97 Crore           1
29.99 Lac            1
4.86 Crore           1
2.62 Crore           1
52.5 Lac             1
90.5 Lac             1
42.5 Lac             1
2.61 Crore           1
65.5 Lac             1
53.2 Lac             1
47.5 Lac             1
4.52 Crore           1
8.44 Crore           1
1.84 Crore           1
13.2 Crore           1
4.16 Crore           1
1.74 Crore           1
4.21 Crore           1
97.5 Lac             1
2.38 Crore           1
2.49 Crore           1
2.64 Crore           1
63.4 Lac             1
2.06 Crore           1
2.07 Crore           1
44 Lac               1
2.32 Crore           1
1.86 Crore           1
85.75 Lac            1
87.99 Lac            1
86.99 Lac            1
2.92 Crore           1
9.3 Crore            1
5.15 Crore           1
49.5 Lac             1
9.2 Crore            1
9.95 Crore           1
16 Lac               1
3.99 Crore           1
64.45 Lac            1
86.92 Lac            1
2.86 Crore           1
7.4 Crore            1
3.78 Crore           1
29.5 Lac             1
3.87 Crore           1
94.99 Lac            1
88.4 Lac             1
37.1 Lac             1
9 Crore              1
57 Lac               1
3.72 Crore           1
19 Lac               1
95.5 Lac             1
70.85 Lac            1
7.52 Crore           1
40.3 Lac             1
96.07 Lac            1
32.5 Lac             1
2.96 Crore           1
1.53 Crore           1
26.9 Lac             1
26.5 Lac             1
73.53 Lac            1
89.77 Lac            1
62.5 Lac             1
Name: count, dtype: int64

In [88]:
df['price']

0                 45 Lac
1                 50 Lac
2                 40 Lac
3             1.47 Crore
4                 70 Lac
5                 41 Lac
6                2 Crore
7              1.8 Crore
8              1.1 Crore
9             4.75 Crore
10                96 Lac
11                29 Lac
12            1.35 Crore
13                95 Lac
14                70 Lac
15            3.95 Crore
16                90 Lac
17            1.05 Crore
18                   NaN
19             2.2 Crore
20            1.01 Crore
21            1.85 Crore
22                86 Lac
23            1.85 Crore
24            2.85 Crore
25      Price on Request
26                42 Lac
27            6.15 Crore
28            6.25 Crore
29                42 Lac
30            1.35 Crore
31             1.6 Crore
32            3.25 Crore
33                45 Lac
34                85 Lac
35                75 Lac
36                82 Lac
37             1.8 Crore
38             29.99 Lac
39                78 Lac
40               2 Crore
41                74 Lac
42             3.2 Crore
43             1.3 Crore
44                25 Lac
45                95 Lac
46            1.99 Crore
47            1.05 Crore
48            1.83 Crore
49            2.25 Crore
50             2.8 Crore
51             1.6 Crore
52                83 Lac
53                83 Lac
54                80 Lac
55            1.25 Crore
56                23 Lac
57                30 Lac
58            1.55 Crore
59                79 Lac
60                50 Lac
61            1.01 Crore
62                95 Lac
63                99 Lac
64             1.1 Crore
65             1.9 Crore
66               1 Crore
67             2.5 Crore
68             1.1 Crore
69                29 Lac
70                55 Lac
71                65 Lac
72                50 Lac
73             31.75 Lac
74                93 Lac
75             1.2 Crore
76                30 Lac
77                56 Lac
78             2.7 Crore
79               1 Crore
80            1.45 Crore
81            1.25 Crore
82                46 Lac
83             4.5 Crore
84                64 Lac
85                28 Lac
86            3.87 Crore
87            1.38 Crore
88                43 Lac
89              28.5 Lac
90             1.1 Crore
91               2 Crore
92                90 Lac
93                90 Lac
94            1.75 Crore
95                93 Lac
96             1.8 Crore
97             2.1 Crore
98               2 Crore
99               2 Crore
100           1.29 Crore
101           2.85 Crore
102            1.1 Crore
103           1.65 Crore
104               24 Lac
105            2.1 Crore
106            1.9 Crore
107            1.1 Crore
108             31.5 Lac
109            1.7 Crore
110               32 Lac
111               45 Lac
112            1.2 Crore
113            2.1 Crore
114               45 Lac
115               42 Lac
116           1.55 Crore
117            1.3 Crore
118           2.75 Crore
119           1.25 Crore
120               42 Lac
121               40 Lac
122               34 Lac
123           1.25 Crore
124            1.5 Crore
125            1.3 Crore
126            1.6 Crore
127            1.5 Crore
128            1.5 Crore
129               90 Lac
130            1.5 Crore
131               80 Lac
132           1.25 Crore
133               26 Lac
134               42 Lac
135            2.5 Crore
136               90 Lac
137               42 Lac
138               50 Lac
139               90 Lac
140            1.3 Crore
141            1.7 Crore
142           1.25 Crore
143           2.91 Crore
144           1.15 Crore
145            1.2 Crore
146            1.5 Crore
147            1.3 Crore
148           1.75 Crore
149               55 Lac
150            2.5 Crore
151               43 Lac
152               80 Lac
153               45 Lac
154               70 Lac
155           1.95 Crore
156               45 Lac
157            1.7 Crore
158            1.1 Crore
159               50 Lac
160            2.8 Crore
161           1.45 Crore
162            2.2 Crore
163               90 Lac
164               40 Lac
165           1.35 Crore
166           1.85 Crore
167               25 Lac
168               88 Lac
169           1.15 Crore
170            1.6 Crore
171               85 Lac
172               75 Lac
173           3.35 Crore
174            1.5 Crore
175           1.65 Crore
176              2 Crore
177           1.75 Crore
178               90 Lac
179           1.25 Crore
180              1 Crore
181           1.08 Crore
182           2.15 Crore
183              1 Crore
184           1.65 Crore
185           1.79 Crore
186            1.8 Crore
187           1.45 Crore
188               22 Lac
189               36 Lac
190               25 Lac
191           1.15 Crore
192           1.65 Crore
193            2.9 Crore
194               60 Lac
195            2.4 Crore
196           1.25 Crore
197           2.15 Crore
198             29.5 Lac
199               38 Lac
200            1.5 Crore
201               39 Lac
202            1.6 Crore
203            1.7 Crore
204           3.25 Crore
205               60 Lac
206               27 Lac
207               95 Lac
208           2.65 Crore
209               36 Lac
210               55 Lac
211           1.32 Crore
212               59 Lac
213               45 Lac
214               90 Lac
215            1.4 Crore
216               95 Lac
217              3 Crore
218           3.67 Crore
219           3.85 Crore
220           3.29 Crore
221           2.33 Crore
222           2.79 Crore
223            3.4 Crore
224               72 Lac
225               40 Lac
226               56 Lac
227            1.1 Crore
228               71 Lac
229               78 Lac
230               40 Lac
231           1.85 Crore
232            1.1 Crore
233           1.41 Crore
234           1.45 Crore
235            2.2 Crore
236            1.1 Crore
237           2.05 Crore
238               60 Lac
239               80 Lac
240               41 Lac
241               90 Lac
242               54 Lac
243               82 Lac
244              1 Crore
245           1.85 Crore
246           1.42 Crore
247               55 Lac
248           2.29 Crore
249               97 Lac
250           8.25 Crore
251               30 Lac
252           1.65 Crore
253           1.99 Crore
254              1 Crore
255           4.25 Crore
256           1.25 Crore
257               95 Lac
258           1.05 Crore
259            4.1 Crore
260               50 Lac
261           1.65 Crore
262            1.6 Crore
263            2.1 Crore
264               90 Lac
265            1.1 Crore
266               92 Lac
267               70 Lac
268               99 Lac
269             71.5 Lac
270             87.5 Lac
271               91 Lac
272           1.25 Crore
273           1.05 Crore
274               66 Lac
275           1.83 Crore
276            52.56 Lac
277               80 Lac
278           1.71 Crore
279               65 Lac
280            1.3 Crore
281               82 Lac
282            5.7 Crore
283               88 Lac
284              4 Crore
285           1.93 Crore
286           3.45 Crore
287            1.7 Crore
288           6.15 Crore
289            1.4 Crore
290           1.48 Crore
291           3.25 Crore
292           1.49 Crore
293               30 Lac
294           3.49 Crore
295           2.15 Crore
296            1.4 Crore
297              2 Crore
298            2.3 Crore
299               54 Lac
300           1.25 Crore
301           1.05 Crore
302           1.25 Crore
303              1 Crore
304            1.7 Crore
305            1.3 Crore
306           2.12 Crore
307            3.9 Crore
308              3 Crore
309            2.2 Crore
310           1.35 Crore
311           1.67 Crore
312               90 Lac
313           2.37 Crore
314           1.98 Crore
315            3.7 Crore
316           4.67 Crore
317           1.29 Crore
318           3.65 Crore
319            1.7 Crore
320           6.15 Crore
321            1.4 Crore
322           1.48 Crore
323           3.49 Crore
324           2.15 Crore
325              2 Crore
326               54 Lac
327           1.25 Crore
328           1.05 Crore
329           1.25 Crore
330              1 Crore
331            1.7 Crore
332            1.3 Crore
333           2.12 Crore
334              3 Crore
335           1.35 Crore
336               90 Lac
337           1.98 Crore
338            3.7 Crore
339           1.29 Crore
340            5.6 Crore
341           1.25 Crore
342           1.27 Crore
343           1.36 Crore
344              1 Crore
345           4.25 Crore
346            1.8 Crore
347           1.25 Crore
348               27 Lac
349            5.5 Crore
350               85 Lac
351           1.07 Crore
352               95 Lac
353               87 Lac
354            4.1 Crore
355           1.27 Crore
356           1.47 Crore
357           3.45 Crore
358           1.18 Crore
359           1.55 Crore
360           3.39 Crore
361           1.54 Crore
362           1.42 Crore
363            1.3 Crore
364           2.25 Crore
365            3.5 Crore
366            4.8 Crore
367               78 Lac
368               88 Lac
369            2.6 Crore
370            3.4 Crore
371            2.9 Crore
372               70 Lac
373            1.5 Crore
374           1.28 Crore
375           2.51 Crore
376            6.5 Crore
377           3.63 Crore
378           1.85 Crore
379           2.45 Crore
380           1.38 Crore
381            5.9 Crore
382              3 Crore
383           2.01 Crore
384            2.1 Crore
385           4.25 Crore
386           2.55 Crore
387              2 Crore
388           3.25 Crore
389            1.6 Crore
390            1.5 Crore
391           3.75 Crore
392               95 Lac
393            1.4 Crore
394           1.56 Crore
395           1.35 Crore
396            1.4 Crore
397           2.26 Crore
398            1.2 Crore
399           2.08 Crore
400           1.75 Crore
401           2.99 Crore
402            2.1 Crore
403           2.87 Crore
404           2.35 Crore
405              3 Crore
406              6 Crore
407           2.35 Crore
408            1.9 Crore
409               72 Lac
410               65 Lac
411           2.34 Crore
412           2.57 Crore
413           1.71 Crore
414           3.79 Crore
415           2.05 Crore
416            5.2 Crore
417            3.2 Crore
418               69 Lac
419           3.75 Crore
420           3.65 Crore
421           5.49 Crore
422           1.05 Crore
423           3.35 Crore
424            2.4 Crore
425           1.71 Crore
426            6.3 Crore
427            2.2 Crore
428           3.25 Crore
429          11.25 Crore
430            3.3 Crore
431           1.51 Crore
432           1.38 Crore
433            4.6 Crore
434            1.4 Crore
435            3.5 Crore
436               99 Lac
437           2.65 Crore
438            2.4 Crore
439           1.65 Crore
440           1.25 Crore
441              4 Crore
442            1.8 Crore
443           1.75 Crore
444           2.35 Crore
445           7.15 Crore
446           1.64 Crore
447            2.8 Crore
448           6.75 Crore
449            3.5 Crore
450            4.6 Crore
451           2.25 Crore
452            2.2 Crore
453           2.85 Crore
454           1.76 Crore
455              1 Crore
456            3.6 Crore
457           1.78 Crore
458               98 Lac
459           2.82 Crore
460           3.21 Crore
461            1.9 Crore
462           1.19 Crore
463           1.35 Crore
464            1.8 Crore
465           1.35 Crore
466            1.7 Crore
467            1.6 Crore
468           2.65 Crore
469            54.99 Lac
470            1.4 Crore
471           1.26 Crore
472            1.7 Crore
473            4.1 Crore
474           1.01 Crore
475           1.45 Crore
476            1.6 Crore
477           2.99 Crore
478            1.9 Crore
479           1.75 Crore
480            1.3 Crore
481           2.95 Crore
482            3.4 Crore
483           3.32 Crore
484               95 Lac
485           1.55 Crore
486           1.54 Crore
487           2.45 Crore
488            2.6 Crore
489           1.83 Crore
490           1.09 Crore
491           1.87 Crore
492           1.05 Crore
493           1.77 Crore
494            2.2 Crore
495               60 Lac
496            1.8 Crore
497               64 Lac
498               75 Lac
499           4.95 Crore
500           4.25 Crore
501           5.31 Crore
502            1.4 Crore
503            2.8 Crore
504            4.1 Crore
505            3.4 Crore
506           3.05 Crore
507           4.25 Crore
508           1.16 Crore
509           3.55 Crore
510            1.8 Crore
511           1.75 Crore
512            1.2 Crore
513           1.52 Crore
514           1.55 Crore
515            2.4 Crore
516           2.35 Crore
517           2.28 Crore
518            1.1 Crore
519            2.3 Crore
520           1.35 Crore
521           2.45 Crore
522               90 Lac
523            2.8 Crore
524            1.4 Crore
525           1.36 Crore
526             98.5 Lac
527             56.2 Lac
528            2.2 Crore
529            1.2 Crore
530           1.33 Crore
531               87 Lac
532           1.09 Crore
533              3 Crore
534           1.75 Crore
535           1.75 Crore
536            3.8 Crore
537            3.5 Crore
538           1.78 Crore
539           1.08 Crore
540           2.03 Crore
541           1.12 Crore
542              2 Crore
543           1.04 Crore
544           1.25 Crore
545           2.05 Crore
546           3.19 Crore
547           3.85 Crore
548            3.2 Crore
549             88.5 Lac
550               49 Lac
551           1.65 Crore
552           2.35 Crore
553            1.4 Crore
554               97 Lac
555           2.35 Crore
556           3.32 Crore
557           1.25 Crore
558            2.8 Crore
559            4.7 Crore
560            1.3 Crore
561               62 Lac
562               80 Lac
563           1.73 Crore
564           4.45 Crore
565            2.3 Crore
566            2.2 Crore
567           2.12 Crore
568           2.25 Crore
569            1.9 Crore
570            4.4 Crore
571           1.75 Crore
572            2.8 Crore
573           4.63 Crore
574           1.32 Crore
575           1.16 Crore
576               27 Lac
577            27.75 Lac
578           1.79 Crore
579           1.55 Crore
580           1.55 Crore
581           3.35 Crore
582            3.5 Crore
583            4.8 Crore
584            1.5 Crore
585           2.78 Crore
586           2.25 Crore
587           2.55 Crore
588           1.25 Crore
589               85 Lac
590           5.25 Crore
591            1.3 Crore
592               75 Lac
593           3.65 Crore
594           1.65 Crore
595           1.25 Crore
596           1.42 Crore
597           1.27 Crore
598           1.65 Crore
599           1.24 Crore
600            2.7 Crore
601           1.98 Crore
602            2.5 Crore
603           2.29 Crore
604           2.98 Crore
605           1.35 Crore
606           1.37 Crore
607           1.55 Crore
608           4.25 Crore
609           1.28 Crore
610           1.95 Crore
611           2.35 Crore
612              5 Crore
613               99 Lac
614           1.95 Crore
615            3.3 Crore
616           4.75 Crore
617            1.5 Crore
618           1.54 Crore
619           1.27 Crore
620           1.17 Crore
621            1.8 Crore
622               80 Lac
623           1.76 Crore
624           2.22 Crore
625           1.24 Crore
626           1.12 Crore
627            1.9 Crore
628           1.35 Crore
629           2.22 Crore
630               90 Lac
631           1.75 Crore
632            66.99 Lac
633           2.95 Crore
634           2.04 Crore
635           2.24 Crore
636           1.31 Crore
637            1.7 Crore
638           1.19 Crore
639           1.75 Crore
640           1.12 Crore
641               92 Lac
642               90 Lac
643            2.3 Crore
644           1.58 Crore
645           4.25 Crore
646           1.68 Crore
647           4.55 Crore
648           2.85 Crore
649           2.35 Crore
650            2.3 Crore
651           2.26 Crore
652           4.78 Crore
653              2 Crore
654           3.75 Crore
655           6.16 Crore
656            5.3 Crore
657               75 Lac
658           1.25 Crore
659              2 Crore
660            1.3 Crore
661           1.75 Crore
662              2 Crore
663           1.78 Crore
664           1.15 Crore
665           1.65 Crore
666               21 Lac
667           2.75 Crore
668           2.72 Crore
669            2.4 Crore
670            4.1 Crore
671           1.12 Crore
672               65 Lac
673            7.5 Crore
674             11 Crore
675           1.26 Crore
676            1.8 Crore
677            5.9 Crore
678            2.9 Crore
679           1.59 Crore
680           2.21 Crore
681           1.48 Crore
682               98 Lac
683           2.04 Crore
684            1.5 Crore
685           1.49 Crore
686            1.2 Crore
687               86 Lac
688             89.5 Lac
689              2 Crore
690           1.85 Crore
691           2.65 Crore
692            1.5 Crore
693           1.75 Crore
694           1.32 Crore
695               80 Lac
696            1.2 Crore
697            6.5 Crore
698           1.17 Crore
699           1.15 Crore
700           2.48 Crore
701           1.35 Crore
702           1.15 Crore
703           2.95 Crore
704            3.4 Crore
705            2.8 Crore
706           2.15 Crore
707           1.76 Crore
708           3.45 Crore
709            3.3 Crore
710           1.75 Crore
711           2.78 Crore
712           1.42 Crore
713            2.4 Crore
714           2.28 Crore
715            1.9 Crore
716           3.25 Crore
717            1.6 Crore
718           4.45 Crore
719               82 Lac
720               50 Lac
721               52 Lac
722               28 Lac
723               29 Lac
724               97 Lac
725               80 Lac
726           1.45 Crore
727               55 Lac
728            1.1 Crore
729            1.4 Crore
730           1.42 Crore
731           2.95 Crore
732            2.6 Crore
733            1.1 Crore
734               75 Lac
735            1.3 Crore
736           1.49 Crore
737           1.19 Crore
738           1.15 Crore
739             99.5 Lac
740               78 Lac
741           1.15 Crore
742               80 Lac
743            2.2 Crore
744           1.55 Crore
745           1.55 Crore
746               90 Lac
747               90 Lac
748               85 Lac
749              3 Crore
750           2.12 Crore
751           1.05 Crore
752           1.65 Crore
753            1.5 Crore
754            3.4 Crore
755            3.5 Crore
756           3.15 Crore
757           5.25 Crore
758           2.78 Crore
759               72 Lac
760           1.55 Crore
761            1.5 Crore
762           3.05 Crore
763           3.83 Crore
764           2.25 Crore
765            1.4 Crore
766           3.75 Crore
767           1.51 Crore
768            2.7 Crore
769           3.35 Crore
770            1.5 Crore
771            2.2 Crore
772           2.55 Crore
773               45 Lac
774           1.18 Crore
775               85 Lac
776           1.49 Crore
777            6.5 Crore
778           1.18 Crore
779               80 Lac
780           1.42 Crore
781              5 Crore
782           1.72 Crore
783           1.95 Crore
784               75 Lac
785           1.72 Crore
786            2.5 Crore
787            1.7 Crore
788           1.14 Crore
789           1.35 Crore
790             27.1 Lac
791            1.4 Crore
792           1.25 Crore
793           1.18 Crore
794            1.1 Crore
795           1.21 Crore
796           3.45 Crore
797           1.95 Crore
798           3.65 Crore
799            2.3 Crore

In [89]:
df[df['price'] == 'Price on Request']

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
25,5 BHK Flat in Sector 1 Gurgaon,the new people apartments,Price on Request,NaN,Built Up area: 4500 (418.06 sq.m.),5 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana",Ground of 1 Floors,NaN,undefined,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Best in class property available at sector 1 l...,NaN,NaN,NaN
1644,4 BHK Flat in Sector 50 Gurgaon,ss hibiscus,Price on Request,NaN,Carpet area: 4800 (445.93 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Sector 50 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,East,5 to 10 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",4bedroom 4800sq.Ft middle floor apartment avai...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Water purifier', 'Swimming Pool',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1972,1 BHK Flat in Sector 31 Gurgaon,raheja atlantis,Price on Request,NaN,Carpet area: 650 (60.39 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,"Pooja Room,Study Room,Servant Room","Yes, Sector 31 Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,East,0 to 1 Year Old,"['Huda Metro Station', 'Reliance Fresh, Indira...",It is my property and good condition and good ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
2054,2 BHK Flat in Sector 79 Gurgaon,supertech araville,Price on Request,NaN,Built Up area: 1295 (120.31 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",15th of 15 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 15th floor (Of 18), super...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5..."
2357,2 BHK Flat in Sector 37D Gurgaon,the millennia 2,Price on Request,NaN,Carpet area: 552 (51.28 sq.m.),2 Bedrooms,1 Bathroom,1 Balcony,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",13rd of 13 Floors,NaN,undefined,"['Shri Balaji Hospital and Trauma Center', 'Sh...","1 bath, unfurnished, 13th floor (Of 13), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2522,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
2549,3 BHK Flat in Sector-2 Sohna,supertech hilltown,Price on Request,NaN,Built Up area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN
2640,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
2959,3 BHK Flat in Sector 104 Gurgaon,godrej summit,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
2972,4 BHK Flat in Gwal Pahari,krrish provence estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
2973,4 BHK Flat in Sector 95 Gurgaon,sidhartha ncr one phase,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [90]:
df = df[df['price'] != 'Price on Request']

In [91]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [92]:
# Now in the price column the price has two unit one is in lac and the other is in crore we will try to convert the lac  into crore so that it can be only one unit

In [93]:
def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [94]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [95]:
df['price'] = df['price'].str.split(' ').apply(treat_price)

In [96]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [97]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [98]:
# price__per_sqft

In [99]:
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 10,000/sq.ft.     19
₹ 12,500/sq.ft.     16
₹ 8,000/sq.ft.      16
₹ 6,666/sq.ft.      13
₹ 5,000/sq.ft.      13
₹ 8,333/sq.ft.      12
₹ 7,500/sq.ft.      12
₹ 6,000/sq.ft.      11
₹ 8,461/sq.ft.       9
₹ 12,000/sq.ft.      8
₹ 7,000/sq.ft.       8
₹ 9,000/sq.ft.       7
₹ 11,111/sq.ft.      6
₹ 6,578/sq.ft.       6
₹ 9,230/sq.ft.       6
₹ 8,888/sq.ft.       6
₹ 8,928/sq.ft.       6
₹ 5,500/sq.ft.       6
₹ 11,500/sq.ft.      6
₹ 5,600/sq.ft.       5
₹ 11,428/sq.ft.      5
₹ 10,714/sq.ft.      5
₹ 4,444/sq.ft.       5
₹ 14,242/sq.ft.      5
₹ 7,641/sq.ft.       5
₹ 8,571/sq.ft.       5
₹ 8,205/sq.ft.       5
₹ 7,142/sq.ft.       5
₹ 16,000/sq.ft.      5
₹ 7,407/sq.ft.       5
₹ 4,666/sq.ft.       5
₹ 4,615/sq.ft.       5
₹ 6,500/sq.ft.       5
₹ 5,556/sq.ft.       5
₹ 5,384/sq.ft.       5
₹ 7,692/sq.ft.       5
₹ 4,854/sq.ft.       4
₹ 8,445/sq.ft.       4
₹ 6,735/sq.ft.       4
₹ 8,358/sq.ft.       4
₹ 7,317/sq.ft.       4
₹ 10,416/sq.ft.      4
₹ 7,250/sq.ft.       4
₹ 13,913/sq.ft.      4
₹ 16,666/sq.ft.      4
₹ 9,822/sq.ft.       4
₹ 5,660/sq.ft.       4
₹ 8,474/sq.ft.       4
₹ 8,500/sq.ft.       4
₹ 4,814/sq.ft.       4
₹ 11,666/sq.ft.      4
₹ 8,139/sq.ft.       4
₹ 7,812/sq.ft.       4
₹ 9,210/sq.ft.       4
₹ 8,163/sq.ft.       4
₹ 14,418/sq.ft.      4
₹ 10,383/sq.ft.      4
₹ 8,484/sq.ft.       4
₹ 15,384/sq.ft.      4
₹ 13,636/sq.ft.      4
₹ 9,090/sq.ft.       4
₹ 7,272/sq.ft.       4
₹ 7,496/sq.ft.       4
₹ 8,043/sq.ft.       4
₹ 8,108/sq.ft.       4
₹ 6,250/sq.ft.       4
₹ 15,000/sq.ft.      4
₹ 8,787/sq.ft.       4
₹ 4,500/sq.ft.       4
₹ 13,750/sq.ft.      4
₹ 8,432/sq.ft.       4
₹ 4,687/sq.ft.       4
₹ 8,784/sq.ft.       4
₹ 8,148/sq.ft.       3
₹ 8,078/sq.ft.       3
₹ 7,549/sq.ft.       3
₹ 8,215/sq.ft.       3
₹ 6,818/sq.ft.       3
₹ 8,222/sq.ft.       3
₹ 4,513/sq.ft.       3
₹ 4,210/sq.ft.       3
₹ 10,204/sq.ft.      3
₹ 14,000/sq.ft.      3
₹ 6,387/sq.ft.       3
₹ 5,833/sq.ft.       3
₹ 14,430/sq.ft.      3
₹ 7,302/sq.ft.       3
₹ 11,363/sq.ft.      3
₹ 11,000/sq.ft.      3
₹ 6,421/sq.ft.       3
₹ 6,644/sq.ft.       3
₹ 9,972/sq.ft.       3
₹ 6,086/sq.ft.       3
₹ 8,400/sq.ft.       3
₹ 16,969/sq.ft.      3
₹ 10,638/sq.ft.      3
₹ 7,954/sq.ft.       3
₹ 9,011/sq.ft.       3
₹ 8,532/sq.ft.       3
₹ 7,179/sq.ft.       3
₹ 5,325/sq.ft.       3
₹ 5,856/sq.ft.       3
₹ 13,392/sq.ft.      3
₹ 8,389/sq.ft.       3
₹ 8,750/sq.ft.       3
₹ 5,878/sq.ft.       3
₹ 8,604/sq.ft.       3
₹ 7,750/sq.ft.       3
₹ 5,319/sq.ft.       3
₹ 16,470/sq.ft.      3
₹ 6,476/sq.ft.       3
₹ 7,948/sq.ft.       3
₹ 7,586/sq.ft.       3
₹ 9,500/sq.ft.       3
₹ 8,080/sq.ft.       3
₹ 7,150/sq.ft.       3
₹ 7,541/sq.ft.       3
₹ 7,467/sq.ft.       3
₹ 14,254/sq.ft.      3
₹ 7,056/sq.ft.       3
₹ 8,606/sq.ft.       3
₹ 9,473/sq.ft.       3
₹ 6,921/sq.ft.       3
₹ 8,620/sq.ft.       3
₹ 8,181/sq.ft.       3
₹ 9,900/sq.ft.       3
₹ 7,865/sq.ft.       3
₹ 7,400/sq.ft.       3
₹ 13,000/sq.ft.      3
₹ 10,555/sq.ft.      3
₹ 4,800/sq.ft.       3
₹ 4,820/sq.ft.       3
₹ 13,870/sq.ft.      3
₹ 5,735/sq.ft.       3
₹ 6,667/sq.ft.       3
₹ 7,083/sq.ft.       3
₹ 8,450/sq.ft.       3
₹ 8,886/sq.ft.       3
₹ 6,542/sq.ft.       3
₹ 10,139/sq.ft.      3
₹ 9,904/sq.ft.       3
₹ 4,105/sq.ft.       3
₹ 6,593/sq.ft.       3
₹ 6,470/sq.ft.       3
₹ 9,615/sq.ft.       3
₹ 5,397/sq.ft.       3
₹ 5,238/sq.ft.       3
₹ 10,500/sq.ft.      3
₹ 6,404/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 6,859/sq.ft.       2
₹ 13,333/sq.ft.      2
₹ 12,250/sq.ft.      2
₹ 6,722/sq.ft.       2
₹ 58/sq.ft.          2
₹ 5,463/sq.ft.       2
₹ 16,858/sq.ft.      2
₹ 8,974/sq.ft.       2
₹ 8,166/sq.ft.       2
₹ 7,631/sq.ft.       2
₹ 11,726/sq.ft.      2
₹ 5,100/sq.ft.       2
₹ 9,022/sq.ft.       2
₹ 12,012/sq.ft.      2
₹ 7,185/sq.ft.       2
₹ 4,307/sq.ft.       2
₹ 6,588/sq.ft.       2
₹ 8,756/sq.ft.       2
₹ 9,482/sq.ft.       2
₹ 5,599/sq.ft.       2
₹ 4,745/sq.ft.       2
₹ 5,517/sq.ft.       2
₹ 8,518/sq.ft.       2
₹ 11,250/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 5,980/sq.ft.       2
₹ 5,828/sq.ft.       2
₹ 6,243/sq.ft.       2
₹ 7,758/sq.ft.       2
₹ 7,863/sq.ft.       2
₹ 5,564/sq.ft.       2
₹ 6,428/sq.ft.       2
₹ 14,303/sq.ft.      2
₹ 5,177/sq.ft.       2
₹ 8,305/sq.ft.       2
₹ 9,589/sq.ft.       2
₹ 5,658/sq.ft.       2
₹ 5,454/sq.ft.       2
₹ 8,424/sq.ft.       2
₹ 7,987/sq.ft.       2
₹ 6,382/sq.ft.       2
₹ 14,683/sq.ft.      2
₹ 6,153/sq.ft.       2
₹ 9,306/sq.ft.       2
₹ 16,363/sq.ft.      2
₹ 13,709/sq.ft.      2
₹ 8,457/sq.ft.       2
₹ 8,024/sq.ft.       2
₹ 6,178/sq.ft.       2
₹ 6,896/sq.ft.       2
₹ 6,353/sq.ft.       2
₹ 33,198/sq.ft.      2
₹ 6,406/sq.ft.       2
₹ 6,839/sq.ft.       2
₹ 7,716/sq.ft.       2
₹ 4,400/sq.ft.       2
₹ 5,982/sq.ft.       2
₹ 8,536/sq.ft.       2
₹ 5,470/sq.ft.       2
₹ 19,000/sq.ft.      2
₹ 8,324/sq.ft.       2
₹ 10,666/sq.ft.      2
₹ 14,285/sq.ft.      2
₹ 7,200/sq.ft.       2
₹ 3,695/sq.ft.       2
₹ 8,412/sq.ft.       2
₹ 5,189/sq.ft.       2
₹ 8,835/sq.ft.       2
₹ 11,992/sq.ft.      2
₹ 7,530/sq.ft.       2
₹ 4,761/sq.ft.       2
₹ 6,465/sq.ft.       2
₹ 9,020/sq.ft.       2
₹ 5,291/sq.ft.       2
₹ 6,811/sq.ft.       2
₹ 9,978/sq.ft.       2
₹ 6,209/sq.ft.       2
₹ 9,074/sq.ft.       2
₹ 7,765/sq.ft.       2
₹ 6,206/sq.ft.       2
₹ 5,284/sq.ft.       2
₹ 6,402/sq.ft.       2
₹ 8,814/sq.ft.       2
₹ 5,614/sq.ft.       2
₹ 8,031/sq.ft.       2
₹ 7,297/sq.ft.       2
₹ 9,550/sq.ft.       2
₹ 6,616/sq.ft.       2
₹ 8,237/sq.ft.       2
₹ 5,150/sq.ft.       2
₹ 14,615/sq.ft.      2
₹ 15,294/sq.ft.      2
₹ 6,702/sq.ft.       2
₹ 5,744/sq.ft.       2
₹ 8,294/sq.ft.       2
₹ 3,477/sq.ft.       2
₹ 12,777/sq.ft.      2
₹ 8,283/sq.ft.       2
₹ 8,411/sq.ft.       2
₹ 9,950/sq.ft.       2
₹ 10,553/sq.ft.      2
₹ 8,517/sq.ft.       2
₹ 9,742/sq.ft.       2
₹ 9,452/sq.ft.       2
₹ 6,774/sq.ft.       2
₹ 8,453/sq.ft.       2
₹ 6,927/sq.ft.       2
₹ 9,139/sq.ft.       2
₹ 13,430/sq.ft.      2
₹ 11,727/sq.ft.      2
₹ 6,190/sq.ft.       2
₹ 10,489/sq.ft.      2
₹ 15,195/sq.ft.      2
₹ 5,929/sq.ft.       2
₹ 5,111/sq.ft.       2
₹ 16,608/sq.ft.      2
₹ 9,565/sq.ft.       2
₹ 5,786/sq.ft.       2
₹ 5,649/sq.ft.       2
₹ 6,985/sq.ft.       2
₹ 15,454/sq.ft.      2
₹ 4,856/sq.ft.       2
₹ 6,571/sq.ft.       2
₹ 21,538/sq.ft.      2
₹ 6,692/sq.ft.       2
₹ 5,252/sq.ft.       2
₹ 13,928/sq.ft.      2
₹ 9,854/sq.ft.       2
₹ 7,850/sq.ft.       2
₹ 7,817/sq.ft.       2
₹ 8,618/sq.ft.       2
₹ 11,125/sq.ft.      2
₹ 6,686/sq.ft.       2
₹ 15,500/sq.ft.      2
₹ 12,444/sq.ft.      2
₹ 8,972/sq.ft.       2
₹ 13,991/sq.ft.      2
₹ 9,433/sq.ft.       2
₹ 10,651/sq.ft.      2
₹ 5,808/sq.ft.       2
₹ 8,279/sq.ft.       2
₹ 4,080/sq.ft.       2
₹ 10,237/sq.ft.      2
₹ 200,000/sq.ft.     2
₹ 9,062/sq.ft.       2
₹ 6,029/sq.ft.       2
₹ 10,545/sq.ft.      2
₹ 7,751/sq.ft.       2
₹ 5,725/sq.ft.       2
₹ 5,528/sq.ft.       2
₹ 9,449/sq.ft.       2
₹ 6,076/sq.ft.       2
₹ 6,825/sq.ft.       2
₹ 6,647/sq.ft.       2
₹ 8,053/sq.ft.       2
₹ 8,903/sq.ft.       2
₹ 9,642/sq.ft.       2
₹ 11,694/sq.ft.      2
₹ 7,223/sq.ft.       2
₹ 13,270/sq.ft.      2
₹ 13,343/sq.ft.      2
₹ 5,820/sq.ft.       2
₹ 19,767/sq.ft.      2
₹ 6,254/sq.ft.       2
₹ 6,217/sq.ft.       2
₹ 5,588/sq.ft.       2
₹ 9,128/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 11,336/sq.ft.      2
₹ 6,455/sq.ft.       2
₹ 7,097/sq.ft.       2
₹ 7,908/sq.ft.       2
₹ 10,596/sq.ft.      2
₹ 7,014/sq.ft.       2
₹ 9,007/sq.ft.       2
₹ 5,825/sq.ft.       2
₹ 8,100/sq.ft.       2
₹ 10,476/sq.ft.      2
₹ 8,733/sq.ft.       2
₹ 7,796/sq.ft.       2
₹ 9,672/sq.ft.       2
₹ 9,135/sq.ft.       2
₹ 7,490/sq.ft.       2
₹ 18,518/sq.ft.      2
₹ 12,222/sq.ft.      2
₹ 9,797/sq.ft.       2
₹ 8,947/sq.ft.       2
₹ 9,922/sq.ft.       2
₹ 5,683/sq.ft.       2
₹ 7,449/sq.ft.       2
₹ 9,105/sq.ft.       2
₹ 7,359/sq.ft.       2
₹ 10,699/sq.ft.      2
₹ 7,608/sq.ft.       2
₹ 8,600/sq.ft.       2
₹ 6,655/sq.ft.       2
₹ 9,620/sq.ft.       2
₹ 5,674/sq.ft.       2
₹ 8,834/sq.ft.       2
₹ 11,529/sq.ft.      2
₹ 6,313/sq.ft.       2
₹ 19,747/sq.ft.      2
₹ 11,627/sq.ft.      2
₹ 7,878/sq.ft.       2
₹ 8,632/sq.ft.       2
₹ 20,687/sq.ft.      2
₹ 5,513/sq.ft.       2
₹ 12,212/sq.ft.      2
₹ 5,896/sq.ft.       2
₹ 6,569/sq.ft.       2
₹ 13,108/sq.ft.      2
₹ 13,076/sq.ft.      2
₹ 6,987/sq.ft.       2
₹ 11,412/sq.ft.      2
₹ 4,857/sq.ft.       2
₹ 9,677/sq.ft.       2
₹ 7,610/sq.ft.       2
₹ 8,720/sq.ft.       2
₹ 15,551/sq.ft.      2
₹ 7,350/sq.ft.       2
₹ 15,416/sq.ft.      2
₹ 6,318/sq.ft.       2
₹ 6,141/sq.ft.       2
₹ 9,743/sq.ft.       2
₹ 8,376/sq.ft.       2
₹ 11,700/sq.ft.      2
₹ 10,516/sq.ft.      2
₹ 6,551/sq.ft.       2
₹ 5,839/sq.ft.       2
₹ 10,936/sq.ft.      2
₹ 7,945/sq.ft.       2
₹ 6,049/sq.ft.       2
₹ 6,679/sq.ft.       2
₹ 9,791/sq.ft.       2
₹ 11,765/sq.ft.      2
₹ 19,882/sq.ft.      2
₹ 17,039/sq.ft.      2
₹ 8,410/sq.ft.       2
₹ 7,574/sq.ft.       2
₹ 8,846/sq.ft.       2
₹ 7,884/sq.ft.       2
₹ 13,383/sq.ft.      2
₹ 7,225/sq.ft.       2
₹ 11,505/sq.ft.      2
₹ 14,785/sq.ft.      2
₹ 13,224/sq.ft.      2
₹ 12,022/sq.ft.      2
₹ 5,681/sq.ft.       2
₹ 16,747/sq.ft.      2
₹ 14,800/sq.ft.      2
₹ 8,521/sq.ft.       2
₹ 11,028/sq.ft.      2
₹ 6,134/sq.ft.       2
₹ 8,290/sq.ft.       2
₹ 13,281/sq.ft.      2
₹ 7,825/sq.ft.       2
₹ 12,782/sq.ft.      2
₹ 8,519/sq.ft.       2
₹ 9,600/sq.ft.       2
₹ 8,072/sq.ft.       2
₹ 14,583/sq.ft.      2
₹ 14,478/sq.ft.      2
₹ 7,174/sq.ft.       2
₹ 4,651/sq.ft.       2
₹ 6,938/sq.ft.       2
₹ 6,597/sq.ft.       2
₹ 3,911/sq.ft.       2
₹ 18,181/sq.ft.      2
₹ 4,271/sq.ft.       2
₹ 8,524/sq.ft.       2
₹ 9,182/sq.ft.       2
₹ 7,248/sq.ft.       2
₹ 10,603/sq.ft.      2
₹ 7,391/sq.ft.       2
₹ 6,333/sq.ft.       2
₹ 16,960/sq.ft.      2
₹ 11,516/sq.ft.      2
₹ 17,619/sq.ft.      2
₹ 8,206/sq.ft.       2
₹ 41,245/sq.ft.      2
₹ 9,851/sq.ft.       2
₹ 8,075/sq.ft.       2
₹ 7,727/sq.ft.       2
₹ 15,998/sq.ft.      2
₹ 13,769/sq.ft.      2
₹ 6,315/sq.ft.       2
₹ 5,671/sq.ft.       2
₹ 14,257/sq.ft.      2
₹ 9,333/sq.ft.       2
₹ 6,053/sq.ft.       2
₹ 14,214/sq.ft.      2
₹ 6,739/sq.ft.       2
₹ 6,325/sq.ft.       2
₹ 6,061/sq.ft.       2
₹ 8,609/sq.ft.       2
₹ 6,429/sq.ft.       2
₹ 6,377/sq.ft.       2
₹ 10,531/sq.ft.      2
₹ 5,038/sq.ft.       2
₹ 5,797/sq.ft.       2
₹ 9,286/sq.ft.       2
₹ 5,056/sq.ft.       2
₹ 6,510/sq.ft.       2
₹ 7,585/sq.ft.       2
₹ 10,601/sq.ft.      2
₹ 14,237/sq.ft.      2
₹ 6,983/sq.ft.       2
₹ 6,538/sq.ft.       2
₹ 6,950/sq.ft.       2
₹ 5,714/sq.ft.       2
₹ 8,433/sq.ft.       2
₹ 15,151/sq.ft.      2
₹ 6,200/sq.ft.       2
₹ 7,846/sq.ft.       2
₹ 8,310/sq.ft.       2
₹ 11,724/sq.ft.      2
₹ 11,715/sq.ft.      2
₹ 6,024/sq.ft.       2
₹ 5,882/sq.ft.       2
₹ 13,500/sq.ft.      2
₹ 9,909/sq.ft.       2
₹ 9,876/sq.ft.       2
₹ 8,504/sq.ft.       2
₹ 8,006/sq.ft.       2
₹ 9,166/sq.ft.       2
₹ 18,000/sq.ft.      2
₹ 6,373/sq.ft.       2
₹ 8,582/sq.ft.       2
₹ 18,271/sq.ft.      2
₹ 7,780/sq.ft.       2
₹ 8,252/sq.ft.       2
₹ 6,789/sq.ft.       2
₹ 16,985/sq.ft.      2
₹ 6,967/sq.ft.       2
₹ 7,627/sq.ft.       2
₹ 6,506/sq.ft.       2
₹ 6,422/sq.ft.       2
₹ 6,111/sq.ft.       2
₹ 10,384/sq.ft.      2
₹ 7,782/sq.ft.       2
₹ 4,909/sq.ft.       2
₹ 11,755/sq.ft.      2
₹ 9,146/sq.ft.       2
₹ 7,396/sq.ft.       2
₹ 10,526/sq.ft.      2
₹ 8,670/sq.ft.       2
₹ 8,897/sq.ft.       2
₹ 10,018/sq.ft.      2
₹ 4,327/sq.ft.       2
₹ 9,027/sq.ft.       2
₹ 6,420/sq.ft.       2
₹ 5,405/sq.ft.       2
₹ 8,035/sq.ft.       2
₹ 8,036/sq.ft.       2
₹ 8,611/sq.ft.       2
₹ 11,333/sq.ft.      2
₹ 15,263/sq.ft.      2
₹ 10,370/sq.ft.      2
₹ 5,641/sq.ft.       2
₹ 5,521/sq.ft.       2
₹ 4,000/sq.ft.       2
₹ 6,812/sq.ft.       2
₹ 8,159/sq.ft.       2
₹ 5,128/sq.ft.       2
₹ 10,599/sq.ft.      2
₹ 6,338/sq.ft.       2
₹ 7,058/sq.ft.       2
₹ 14,545/sq.ft.      2
₹ 5,424/sq.ft.       2
₹ 5,899/sq.ft.       2
₹ 9,025/sq.ft.       2
₹ 7,857/sq.ft.       2
₹ 9,263/sq.ft.       2
₹ 6,189/sq.ft.       2
₹ 4,818/sq.ft.       1
₹ 24,688/sq.ft.      1
₹ 7,164/sq.ft.       1
₹ 6,426/sq.ft.       1
₹ 13,939/sq.ft.      1
₹ 14,444/sq.ft.      1
₹ 12,244/sq.ft.      1
₹ 6,089/sq.ft.       1
₹ 14,118/sq.ft.      1
₹ 10,882/sq.ft.      1
₹ 10,156/sq.ft.      1
₹ 7,539/sq.ft.       1
₹ 9,266/sq.ft.       1
₹ 26,936/sq.ft.      1
₹ 16,580/sq.ft.      1
₹ 6,493/sq.ft.       1
₹ 16,750/sq.ft.      1
₹ 24,300/sq.ft.      1
₹ 6,514/sq.ft.       1
₹ 15,826/sq.ft.      1
₹ 8,669/sq.ft.       1
₹ 10,007/sq.ft.      1
₹ 17,285/sq.ft.      1
₹ 9,650/sq.ft.       1
₹ 6,376/sq.ft.       1
₹ 11,738/sq.ft.      1
₹ 12,325/sq.ft.      1
₹ 8,250/sq.ft.       1
₹ 13,878/sq.ft.      1
₹ 7,059/sq.ft.       1
₹ 9,036/sq.ft.       1
₹ 10,264/sq.ft.      1
₹ 7,065/sq.ft.       1
₹ 5,412/sq.ft.       1
₹ 6,523/sq.ft.       1
₹ 15,240/sq.ft.      1
₹ 12,110/sq.ft.      1
₹ 8,444/sq.ft.       1
₹ 5,720/sq.ft.       1
₹ 7,137/sq.ft.       1
₹ 6,768/sq.ft.       1
₹ 11,379/sq.ft.      1
₹ 14,074/sq.ft.      1
₹ 11,572/sq.ft.      1
₹ 12,400/sq.ft.      1
₹ 11,497/sq.ft.      1
₹ 11,559/sq.ft.      1
₹ 4,456/sq.ft.       1
₹ 6,708/sq.ft.       1
₹ 13,921/sq.ft.      1
₹ 10,761/sq.ft.      1
₹ 3,666/sq.ft.       1
₹ 12,144/sq.ft.      1
₹ 8,095/sq.ft.       1
₹ 14,536/sq.ft.      1
₹ 11,580/sq.ft.      1
₹ 10,953/sq.ft.      1
₹ 11,209/sq.ft.      1
₹ 9,387/sq.ft.       1
₹ 7,308/sq.ft.       1
₹ 4,022/sq.ft.       1
₹ 6,741/sq.ft.       1
₹ 12,009/sq.ft.      1
₹ 6,728/sq.ft.       1
₹ 21,013/sq.ft.      1
₹ 15,560/sq.ft.      1
₹ 35,483/sq.ft.      1
₹ 4,723/sq.ft.       1
₹ 6,215/sq.ft.       1
₹ 6,628/sq.ft.       1
₹ 11,525/sq.ft.      1
₹ 5,246/sq.ft.       1
₹ 9,091/sq.ft.       1
₹ 4,603/sq.ft.       1
₹ 8,724/sq.ft.       1
₹ 5,897/sq.ft.       1
₹ 5,571/sq.ft.       1
₹ 9,767/sq.ft.       1
₹ 24,211/sq.ft.      1
₹ 23,401/sq.ft.      1
₹ 10,418/sq.ft.      1
₹ 18,090/sq.ft.      1
₹ 9,203/sq.ft.       1
₹ 9,463/sq.ft.       1
₹ 4,531/sq.ft.       1
₹ 7,486/sq.ft.       1
₹ 6,556/sq.ft.       1
₹ 14,110/sq.ft.      1
₹ 5,859/sq.ft.       1
₹ 6,587/sq.ft.       1
₹ 10,697/sq.ft.      1
₹ 4,694/sq.ft.       1
₹ 10,365/sq.ft.      1
₹ 8,387/sq.ft.       1
₹ 12,169/sq.ft.      1
₹ 8,837/sq.ft.       1
₹ 7,882/sq.ft.       1
₹ 8,863/sq.ft.       1
₹ 11,963/sq.ft.      1
₹ 5,584/sq.ft.       1
₹ 10,262/sq.ft.      1
₹ 7,402/sq.ft.       1
₹ 14,727/sq.ft.      1
₹ 21,519/sq.ft.      1
₹ 8,264/sq.ft.       1
₹ 33,209/sq.ft.      1
₹ 6,052/sq.ft.       1
₹ 6,534/sq.ft.       1
₹ 14,987/sq.ft.      1
₹ 9,474/sq.ft.       1
₹ 6,060/sq.ft.       1
₹ 5,777/sq.ft.       1
₹ 10,028/sq.ft.      1
₹ 10,815/sq.ft.      1
₹ 8,522/sq.ft.       1
₹ 14,202/sq.ft.      1
₹ 5,930/sq.ft.       1
₹ 4,716/sq.ft.       1
₹ 8,062/sq.ft.       1
₹ 5,432/sq.ft.       1
₹ 6,002/sq.ft.       1
₹ 11,276/sq.ft.      1
₹ 6,286/sq.ft.       1
₹ 14,097/sq.ft.      1
₹ 13,758/sq.ft.      1
₹ 10,004/sq.ft.      1
₹ 4,301/sq.ft.       1
₹ 6,535/sq.ft.       1
₹ 8,825/sq.ft.       1
₹ 13,269/sq.ft.      1
₹ 7,389/sq.ft.       1
₹ 11,825/sq.ft.      1
₹ 11,741/sq.ft.      1
₹ 5,390/sq.ft.       1
₹ 7,116/sq.ft.       1
₹ 5,510/sq.ft.       1
₹ 6,310/sq.ft.       1
₹ 10,071/sq.ft.      1
₹ 5,490/sq.ft.       1
₹ 5,637/sq.ft.       1
₹ 9,639/sq.ft.       1
₹ 8,514/sq.ft.       1
₹ 8,998/sq.ft.       1
₹ 7,242/sq.ft.       1
₹ 7,096/sq.ft.       1
₹ 12,352/sq.ft.      1
₹ 11,713/sq.ft.      1
₹ 6,106/sq.ft.       1
₹ 21,577/sq.ft.      1
₹ 6,346/sq.ft.       1
₹ 12,658/sq.ft.      1
₹ 17,488/sq.ft.      1
₹ 20,388/sq.ft.      1
₹ 4,927/sq.ft.       1
₹ 14,843/sq.ft.      1
₹ 17,000/sq.ft.      1
₹ 5,762/sq.ft.       1
₹ 9,136/sq.ft.       1
₹ 12,484/sq.ft.      1
₹ 11,633/sq.ft.      1
₹ 4,308/sq.ft.       1
₹ 13,342/sq.ft.      1
₹ 9,459/sq.ft.       1
₹ 13,064/sq.ft.      1
₹ 9,102/sq.ft.       1
₹ 5,826/sq.ft.       1
₹ 10,723/sq.ft.      1
₹ 9,375/sq.ft.       1
₹ 5,931/sq.ft.       1
₹ 17,615/sq.ft.      1
₹ 19,174/sq.ft.      1
₹ 10,350/sq.ft.      1
₹ 8,040/sq.ft.       1
₹ 7,826/sq.ft.       1
₹ 7,525/sq.ft.       1
₹ 6,862/sq.ft.       1
₹ 8,270/sq.ft.       1
₹ 4,458/sq.ft.       1
₹ 15,561/sq.ft.      1
₹ 15,317/sq.ft.      1
₹ 6,530/sq.ft.       1
₹ 8,151/sq.ft.       1
₹ 11,817/sq.ft.      1
₹ 15,590/sq.ft.      1
₹ 10,529/sq.ft.      1
₹ 6,032/sq.ft.       1
₹ 6,227/sq.ft.       1
₹ 7,917/sq.ft.       1
₹ 10,727/sq.ft.      1
₹ 5,590/sq.ft.       1
₹ 10,037/sq.ft.      1
₹ 5,548/sq.ft.       1
₹ 8,395/sq.ft.       1
₹ 46,917/sq.ft.      1
₹ 8,704/sq.ft.       1
₹ 5,181/sq.ft.       1
₹ 9,024/sq.ft.       1
₹ 6,295/sq.ft.       1
₹ 6,326/sq.ft.       1
₹ 6,071/sq.ft.       1
₹ 8,920/sq.ft.       1
₹ 16,256/sq.ft.      1
₹ 9,627/sq.ft.       1
₹ 6,170/sq.ft.       1
₹ 10,786/sq.ft.      1
₹ 7,355/sq.ft.       1
₹ 6,625/sq.ft.       1
₹ 15,348/sq.ft.      1
₹ 8,111/sq.ft.       1
₹ 1,384/sq.ft.       1
₹ 8,023/sq.ft.       1
₹ 14,335/sq.ft.      1
₹ 8,708/sq.ft.       1
₹ 9,125/sq.ft.       1
₹ 7,380/sq.ft.       1
₹ 7,777/sq.ft.       1
₹ 7,180/sq.ft.       1
₹ 15,360/sq.ft.      1
₹ 13,126/sq.ft.      1
₹ 4,907/sq.ft.       1
₹ 12,047/sq.ft.      1
₹ 5,263/sq.ft.       1
₹ 9,641/sq.ft.       1
₹ 7,035/sq.ft.       1
₹ 9,039/sq.ft.       1
₹ 6,979/sq.ft.       1
₹ 9,169/sq.ft.       1
₹ 41,666/sq.ft.      1
₹ 10,799/sq.ft.      1
₹ 8,866/sq.ft.       1
₹ 12,589/sq.ft.      1
₹ 5,883/sq.ft.       1
₹ 10,853/sq.ft.      1
₹ 10,200/sq.ft.      1
₹ 5,531/sq.ft.       1
₹ 6,912/sq.ft.       1
₹ 6,104/sq.ft.       1
₹ 7,547/sq.ft.       1
₹ 9,497/sq.ft.       1
₹ 5,991/sq.ft.       1
₹ 4,746/sq.ft.       1
₹ 13,296/sq.ft.      1
₹ 8,840/sq.ft.       1
₹ 12,592/sq.ft.      1
₹ 8,856/sq.ft.       1
₹ 10,539/sq.ft.      1
₹ 11,764/sq.ft.      1
₹ 3,600/sq.ft.       1
₹ 8,553/sq.ft.       1
₹ 4,579/sq.ft.       1
₹ 7,443/sq.ft.       1
₹ 5,775/sq.ft.       1
₹ 9,030/sq.ft.       1
₹ 7,321/sq.ft.       1
₹ 6,894/sq.ft.       1
₹ 8,011/sq.ft.       1
₹ 5,120/sq.ft.       1
₹ 10,481/sq.ft.      1
₹ 9,393/sq.ft.       1
₹ 10,005/sq.ft.      1
₹ 5,759/sq.ft.       1
₹ 7,971/sq.ft.       1
₹ 10,465/sq.ft.      1
₹ 4,646/sq.ft.       1
₹ 13,589/sq.ft.      1
₹ 11,061/sq.ft.      1
₹ 10,656/sq.ft.      1
₹ 4,098/sq.ft.       1
₹ 7,360/sq.ft.       1
₹ 7,754/sq.ft.       1
₹ 11,605/sq.ft.      1
₹ 6,790/sq.ft.       1
₹ 6,932/sq.ft.       1
₹ 4,736/sq.ft.       1
₹ 11,233/sq.ft.      1
₹ 7,176/sq.ft.       1
₹ 6,641/sq.ft.       1
₹ 11,989/sq.ft.      1
₹ 12,134/sq.ft.      1
₹ 6,408/sq.ft.       1
₹ 8,320/sq.ft.       1
₹ 7,769/sq.ft.       1
₹ 10,755/sq.ft.      1
₹ 7,567/sq.ft.       1
₹ 8,256/sq.ft.       1
₹ 8,790/sq.ft.       1
₹ 7,636/sq.ft.       1
₹ 6,016/sq.ft.       1
₹ 6,159/sq.ft.       1
₹ 3,567/sq.ft.       1
₹ 6,975/sq.ft.       1
₹ 5,358/sq.ft.       1
₹ 8,707/sq.ft.       1
₹ 3,158/sq.ft.       1
₹ 7,991/sq.ft.       1
₹ 9,849/sq.ft.       1
₹ 5,261/sq.ft.       1
₹ 21,922/sq.ft.      1
₹ 3,152/sq.ft.       1
₹ 11,805/sq.ft.      1
₹ 16,959/sq.ft.      1
₹ 6,475/sq.ft.       1
₹ 5,607/sq.ft.       1
₹ 12,542/sq.ft.      1
₹ 8,818/sq.ft.       1
₹ 5,076/sq.ft.       1
₹ 9,843/sq.ft.       1
₹ 14,379/sq.ft.      1
₹ 10,825/sq.ft.      1
₹ 5,910/sq.ft.       1
₹ 14,040/sq.ft.      1
₹ 7,623/sq.ft.       1
₹ 9,933/sq.ft.       1
₹ 7,807/sq.ft.       1
₹ 4,961/sq.ft.       1
₹ 8,160/sq.ft.       1
₹ 15,510/sq.ft.      1
₹ 9,745/sq.ft.       1
₹ 8,695/sq.ft.       1
₹ 7,787/sq.ft.       1
₹ 14,598/sq.ft.      1
₹ 15,130/sq.ft.      1
₹ 11,966/sq.ft.      1
₹ 6,815/sq.ft.       1
₹ 13,318/sq.ft.      1
₹ 8,622/sq.ft.       1
₹ 8,769/sq.ft.       1
₹ 11,583/sq.ft.      1
₹ 12,732/sq.ft.      1
₹ 6,225/sq.ft.       1
₹ 9,050/sq.ft.       1
₹ 18,492/sq.ft.      1
₹ 11,338/sq.ft.      1
₹ 10,283/sq.ft.      1
₹ 17,691/sq.ft.      1
₹ 16,454/sq.ft.      1
₹ 4,637/sq.ft.       1
₹ 10,967/sq.ft.      1
₹ 6,330/sq.ft.       1
₹ 5,479/sq.ft.       1
₹ 7,268/sq.ft.       1
₹ 7,964/sq.ft.       1
₹ 6,653/sq.ft.       1
₹ 7,290/sq.ft.       1

In [100]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')

In [101]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [102]:
# BEDROOMS 
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [103]:
df['bedRoom'].isnull().sum()

np.int64(9)

In [104]:
df = df[~df['bedRoom'].isnull()]

In [105]:
df['bedRoom'].isnull().sum()

np.int64(0)

In [106]:

df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype('int')

In [107]:
df.head(1)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [108]:
df['bathroom'].value_counts()

bathroom
2 Bathrooms    1044
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64

In [109]:
df['bathroom'].isnull().sum()

np.int64(0)

In [110]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype('int')

In [111]:
df.head(1)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [112]:
df['balcony'].value_counts()

balcony
3 Balconies     974
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [113]:
df['balcony'].isnull().sum()

np.int64(0)

In [114]:
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2866,3 BHK Flat in Sector 76 Gurgaon,corona gracieux,1.08,5510.0,Super Built up area 1960(182.09 sq.m.),3,3,3 Balconies,Servant Room,"Sector 76 Gurgaon, Gurgaon, Haryana",1st of 13 Floors,NaN,0 to 1 Year Old,"['Entertainland Mall', 'Delhi Ajmer Expressway...",Its a first floor big property. Being on first...,NaN,"['Feng Shui / Vaastu Compliant', 'Lift(s)', 'M...",NaN
1545,2 BHK Flat in Sector 93 Gurgaon,signature global orchard avenue,0.36,6715.0,Carpet area: 543.53 (50.5 sq.m.),2,2,2 Balconies,NaN,"604, Sector 93 Gurgaon, Gurgaon, Haryana",6th of 14 Floors,North,1 to 5 Year Old,"['JMS Crosswalk Mall', 'Reliance Trends Newtow...",2bhk raw at 36.50l for urgent to sell\nSignatu...,NaN,"['Power Back-up', 'Lift(s)', 'No open drainage...","['Green Area4 out of 5', 'Construction4 out of..."
1211,2 BHK Flat in Sector 107 Gurgaon,m3m woodshire,0.90,6588.0,Super Built up area 1366(126.91 sq.m.),2,2,3+ Balconies,NaN,"Sector 107 Gurgaon, Gurgaon, Haryana",4th of 14 Floors,NaN,1 to 5 Year Old,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...",This lovely 2 bhk apartment/flat in sector 107...,NaN,"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area4.5 out of 5', 'Construction5 out ..."
881,4 BHK Flat in Sector 108 Gurgaon,experion the heartsong,2.00,7196.0,Super Built up area 2779(258.18 sq.m.)Built Up...,4,4,3+ Balconies,"Servant Room,Pooja Room","802, Sector 108 Gurgaon, Gurgaon, Haryana",10th of 14 Floors,North-East,1 to 5 Year Old,"['Galleria 108 Mall', 'Dwarka Expressway', 'Ce...",This beautiful 4 bhk flat in sector 108 gurgao...,"['7 Fan', '1 Exhaust Fan', '4 Geyser', '7 Ligh...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
2421,2 BHK Flat in Sector 84 Gurgaon,alpha corp gurgaonone,1.20,9448.0,Super Built up area 1270(117.99 sq.m.),2,2,1 Balcony,NaN,"Sector 84 Gurgaon, Gurgaon, Haryana",6th of 26 Floors,South-West,1 to 5 Year Old,"['Delhi Public School', 'Raheja Market', 'Sapp...",We are the proud owners of this 2 bhk apartmen...,NaN,"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction5 out of..."

In [115]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [116]:
df.head(1)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [117]:
# Now let's work on the additionalRoom

In [118]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Servant Room,Study Room                            8
Study Room,Pooja Room                              8
Study Room,Servant Room,Store Room                 7
Pooja Room,Servant Room,Others                     6
Servant Room,Study Room,Pooja Room,Store Room      6
Pooja Room,Store Room                              6
Others,Servant Room                                6
Pooja Room,Others                                  6
Study Room,Servant Room,Others                     5
Pooja Room,Study Room,Store Room                   4
Pooja Room,Store Room,Study Room,Servant Room      4
Study Room,Pooja Room,Store Room                   3
Store Room,Servant Room                            3
Servant Room,Pooja Room,Study Room,Store Room      3
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Servant Room,Study Room,Store Room                 2
Study Room,Pooja Room,Servant Room                 2
Servant Room,Others,Store Room,Pooja Room          2
Pooja Room,Study Room,Others                       2
Store Room,Pooja Room,Servant Room                 1
Pooja Room,Study Room,Store Room,Servant Room      1
Pooja Room,Servant Room,Study Room,Store Room      1
Servant Room,Pooja Room,Store Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Study Room,Servant Room,Pooja Room                 1
Servant Room,Pooja Room,Store Room,Study Room      1
Study Room,Store Room                              1
Store Room,Study Room                              1
Servant Room,Pooja Room,Study Room                 1
Servant Room,Study Room,Pooja Room                 1
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [119]:
df['additionalRoom'].value_counts().shape

(49,)

In [120]:
df['additionalRoom'].isnull().sum()

np.int64(1305)

In [121]:
df['additionalRoom'].fillna('not available', inplace = True)

/var/folders/_8/bm818y_17hq8trchxblt3ct40000gn/T/ipykernel_22269/3716319996.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('not available', inplace = True)

In [122]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [123]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [124]:
df.sample(10)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2202,3 BHK Flat in Sector 61 Gurgaon,smart world orchard,2.55,15644.0,Carpet area: 1630 (151.43 sq.m.),3,3,2,others,"Sector 61 Gurgaon, Gurgaon, Haryana",4th of 4 Floors,NaN,Within 6 months,"['Sector 55-56 Metro station', 'Bestech Centra...",This 3 bhk apartment is available for sale in ...,"['6 AC', '1 Chimney', '1 Modular Kitchen', 'No...","['Security / Fire Alarm', 'Lift(s)', 'Maintena...",NaN
1007,2 BHK Flat in Sector 66 Gurgaon,ireo uptown,1.85,12567.0,Super Built up area 1472(136.75 sq.m.)Built Up...,2,3,3,"others,servant room","Sector 66 Gurgaon, Gurgaon, Haryana",16th of 25 Floors,South-East,1 to 5 Year Old,"['Hub 66', 'Shiksha Bharti Public School', 'VI...",This is a meticulously designed 2 bhk resale a...,"['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
598,4 BHK Flat in Sector 90 Gurgaon,dlf regal gardens,1.65,7449.0,Super Built up area 2215(205.78 sq.m.)Built Up...,4,4,3+,others,"Middle Floor, Sector 90 Gurgaon, Gurgaon, Haryana",8th of 19 Floors,East,1 to 5 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...",Dlf regal gardens sec-90.\nThis is a well - De...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4.5 out ..."
1997,2 BHK Flat in Sector 111 Gurgaon,tashee capital gateway,0.96,6500.0,Super Built up area 1478(137.31 sq.m.),2,2,1,study room,NaN,4th of 18 Floors,North,Dec 2023,"['Global Foyer Mall', 'Dwarka Expy, Sai Kunj, ...",The property is a 2bhk with extra space may us...,NaN,"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
1191,4 BHK Flat in Sector 70A Gurgaon,bptp astaire gardens,1.60,8658.0,Super Built up area 1848(171.68 sq.m.)Built Up...,4,4,3,"study room,others","H33, Sector 70A Gurgaon, Gurgaon, Haryana",1st of 3 Floors,NaN,1 to 5 Year Old,"['Sector 54 Chowk Metro Station', 'Airia Mall'...",Bptp astaire gardens is one of gurgaon's most ...,"['1 Fan', '1 Light', '2 Chimney', '4 AC', 'No ...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction5 out of..."
866,3 BHK Flat in Sector 83 Gurgaon,vatika city homes,1.05,8571.0,Super Built up area 1740(161.65 sq.m.)Carpet a...,3,3,3,pooja room,"Block B, Sector 83 Gurgaon, Gurgaon, Haryana",8th of 8 Floors,South-East,5 to 10 Year Old,"['Kisan Mandi', 'Vatika City Centre', 'Manesar...",It is a part of. The apartment is well-Ventila...,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '5 Li...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4 out of..."
1278,3 BHK Flat in Sector 65 Gurgaon,m3m golfestate,6.10,18138.0,Super Built up area 3363(312.43 sq.m.)Carpet a...,3,3,3,"study room,servant room","Sector 65 Gurgaon, Gurgaon, Haryana",19th of 40 Floors,North-East,5 to 10 Year Old,"['Sector 54 Chowk Metro Station', 'Sahara Mall...",M3m golfestate is one of gurgaon's most sought...,"['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '5 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
473,3 BHK Flat in Sector 22 Gurgaon,ambience creacions,4.10,28101.0,Super Built up area 2781(258.36 sq.m.)Carpet a...,3,3,3+,not available,"101, Sector 22 Gurgaon, Gurgaon, Haryana",2nd of 20 Floors,North-East,0 to 1 Year Old,"['Moulsari Avenue', 'Ambience Mall', 'Old Delh...",Closer to highway nd accessible to near shops,"['1 Fan', '1 Fridge', '1 Geyser', '1 Stove', '...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1036,3 BHK Flat in Sector 102 Gurgaon,emaar gurgaon greens,1.39,8424.0,Super Built up area 1650(153.29 sq.m.),3,3,3,servant room,"Sector 102 Gurgaon, Gurgaon, Haryana",7th of 14 Floors,West,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...","Situated in sector 102 gurgaon, emaar gurgaon ...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction4 out of..."
879,3 BHK Flat in Sector 54 Gurgaon,sunischit apartments,1.69,7954.0,Super Built up area 2200(204.39 sq.m.),3,3,3+,servant room,"Middle Floor, Sector 54 Gurgaon, Gurgaon, Haryana",5th of 9 Floors,North,10+ Year Old,"['Sector 54 chowk metro station', 'Sector metr...",This lovely 3 bhk apartment/flat in sector 54 ...,"['3 Wardrobe', '1 Water Purifier', '7 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [125]:
df.head(3)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [126]:
# Floor number
df['floorNum'].value_counts()

floorNum
2nd   of 4 Floors           74
3rd   of 4 Floors           71
4th   of 4 Floors           62
1st   of 4 Floors           61
12nd   of 14 Floors         49
14th   of 14 Floors         48
Ground of 14 Floors         40
10th   of 14 Floors         35
7th   of 14 Floors          35
8th   of 14 Floors          34
4th   of 14 Floors          28
6th   of 14 Floors          27
2nd   of 2 Floors           26
1st   of 14 Floors          26
3rd   of 3 Floors           26
8th   of 19 Floors          24
5th   of 14 Floors          24
3rd   of 14 Floors          24
1st   of 1 Floors           23
9th   of 9 Floors           23
9th   of 14 Floors          23
11st   of 14 Floors         23
2nd   of 3 Floors           22
5th   of 12 Floors          22
2nd   of 14 Floors          21
8th   of 18 Floors          20
10th   of 19 Floors         18
6th   of 18 Floors          18
7th   of 15 Floors          17
Ground of 1 Floors          17
7th   of 18 Floors          17
10th   of 18 Floors         17
12nd   of 12 Floors         17
9th   of 13 Floors          17
5th   of 15 Floors          16
3rd   of 18 Floors          16
2nd   of 12 Floors          15
6th   of 12 Floors          15
9th   of 15 Floors          15
1st   of 3 Floors           15
6th   of 19 Floors          14
1st   of 2 Floors           13
10th   of 26 Floors         13
3rd   of 13 Floors          13
6th   of 10 Floors          13
5th   of 5 Floors           13
Ground of 4 Floors          13
7th   of 7 Floors           13
10th   of 10 Floors         12
6th   of 15 Floors          12
8th   of 12 Floors          11
16th   of 19 Floors         11
8th   of 8 Floors           11
9th   of 26 Floors          11
15th   of 19 Floors         11
11st   of 18 Floors         11
9th   of 24 Floors          11
17th   of 17 Floors         11
4th   of 10 Floors          11
6th   of 6 Floors           11
4th   of 13 Floors          11
4th   of 12 Floors          10
6th   of 13 Floors          10
3rd   of 5 Floors           10
7th   of 26 Floors          10
2nd   of 19 Floors          10
7th   of 13 Floors          10
1st   of 26 Floors          10
10th   of 12 Floors         10
7th   of 21 Floors          10
12nd   of 18 Floors         10
4th   of 15 Floors          10
3rd   of 9 Floors           10
15th   of 29 Floors          9
3rd   of 12 Floors           9
8th   of 22 Floors           9
18th   of 19 Floors          9
14th   of 19 Floors          9
9th   of 20 Floors           9
13rd   of 14 Floors          9
8th   of 15 Floors           9
7th   of 17 Floors           9
14th   of 15 Floors          9
12nd   of 17 Floors          9
5th   of 18 Floors           9
6th   of 26 Floors           9
7th   of 12 Floors           9
6th   of 16 Floors           9
3rd   of 15 Floors           8
9th   of 18 Floors           8
5th   of 13 Floors           8
3rd   of 19 Floors           8
1st   of 19 Floors           8
12nd   of 24 Floors          8
8th   of 24 Floors           8
9th   of 12 Floors           8
2nd   of 15 Floors           8
12nd   of 26 Floors          8
10th   of 13 Floors          8
8th   of 26 Floors           8
8th   of 13 Floors           8
12nd   of 19 Floors          8
10th   of 17 Floors          8
4th   of 26 Floors           8
2nd   of 5 Floors            8
2nd   of 8 Floors            8
5th   of 9 Floors            8
14th   of 24 Floors          8
2nd   of 10 Floors           7
13rd   of 13 Floors          7
8th   of 21 Floors           7
7th   of 19 Floors           7
12nd   of 15 Floors          7
9th   of 19 Floors           7
5th   of 29 Floors           7
11st   of 24 Floors          7
2nd   of 13 Floors           7
16th   of 16 Floors          7
8th   of 10 Floors           7
12nd   of 13 Floors          7
1st   of 13 Floors           7
4th   of 19 Floors           7
2nd   of 17 Floors           7
11st   of 11 Floors          7
5th   of 20 Floors           7
11st   of 13 Floors          7
10th   of 21 Floors          7
11st   of 26 Floors          7
5th   of 10 Floors           6
Ground of 15 Floors          6
4th   of 17 Floors           6
11st   of 12 Floors          6
7th   of 20 Floors           6
16th   of 18 Floors          6
5th   of 25 Floors           6
5th   of 22 Floors           6
14th   of 27 Floors          6
12nd   of 22 Floors          6
Ground of 16 Floors          6
17th   of 19 Floors          6
1st   of 10 Floors           6
2nd   of 20 Floors           6
10th   of 15 Floors          6
19th   of 19 Floors          6
15th   of 15 Floors          6
10th   of 20 Floors          6
3rd   of 25 Floors           6
11st   of 19 Floors          6
Ground of 3 Floors           6
6th   of 9 Floors            6
1st   of 5 Floors            6
10th   of 29 Floors          6
4th   of 18 Floors           6
9th   of 30 Floors           5
9th   of 11 Floors           5
12nd   of 21 Floors          5
14th   of 16 Floors          5
4th   of 27 Floors           5
Ground of 19 Floors          5
10th   of 24 Floors          5
Ground of 12 Floors          5
15th   of 21 Floors          5
1st   of 15 Floors           5
18th   of 29 Floors          5
10th   of 27 Floors          5
7th   of 8 Floors            5
15th   of 18 Floors          5
8th   of 9 Floors            5
6th   of 11 Floors           5
4th   of 9 Floors            5
11st   of 25 Floors          5
6th   of 20 Floors           5
16th   of 26 Floors          5
8th   of 30 Floors           5
10th   of 25 Floors          5
15th   of 28 Floors          5
12nd   of 29 Floors          5
1st   of 12 Floors           5
11st   of 16 Floors          5
11st   of 29 Floors          5
Ground of 21 Floors          5
7th   of 27 Floors           5
11st   of 30 Floors          5
14th   of 29 Floors          5
5th   of 19 Floors           5
1st   of 7 Floors            5
4th   of 22 Floors           5
6th   of 17 Floors           5
9th   of 22 Floors           5
3rd   of 20 Floors           5
5th   of 8 Floors            5
3rd   of 10 Floors           4
3rd   of 17 Floors           4
14th   of 21 Floors          4
3rd   of 22 Floors           4
7th   of 10 Floors           4
18th   of 32 Floors          4
15th   of 32 Floors          4
19th   of 40 Floors          4
11st   of 20 Floors          4
14th   of 18 Floors          4
23rd   of 26 Floors          4
11st   of 17 Floors          4
7th   of 11 Floors           4
13rd   of 19 Floors          4
17th   of 25 Floors          4
8th   of 16 Floors           4
20th   of 26 Floors          4
19th   of 24 Floors          4
13rd   of 21 Floors          4
Ground of 13 Floors          4
5th   of 24 Floors           4
8th   of 20 Floors           4
25th   of 25 Floors          4
17th   of 26 Floors          4
2nd   of 16 Floors           4
20th   of 20 Floors          4
2nd   of 11 Floors           4
11st   of 15 Floors          4
5th   of 16 Floors           4
2nd   of 9 Floors            4
17th   of 18 Floors          4
6th   of 30 Floors           4
5th   of 23 Floors           4
Ground of 17 Floors          4
3rd   of 11 Floors           4
22nd   of 30 Floors          4
22nd   of 24 Floors          4
14th   of 17 Floors          4
15th   of 23 Floors          4
1st   of 18 Floors           4
7th   of 9 Floors            4
17th   of 24 Floors          4
15th   of 16 Floors          4
14th   of 26 Floors          4
15th   of 25 Floors          4
12nd   of 16 Floors          4
4th   of 8 Floors            4
13rd   of 25 Floors          4
7th   of 24 Floors           4
15th   of 26 Floors          4
9th   of 10 Floors           4
12nd   of 30 Floors          4
6th   of 22 Floors           3
7th   of 23 Floors           3
8th   of 11 Floors           3
16th   of 20 Floors          3
26th   of 30 Floors          3
13rd   of 15 Floors          3
9th   of 16 Floors           3
10th   of 30 Floors          3
6th   of 24 Floors           3
1st   of 25 Floors           3
5th   of 30 Floors           3
12nd   of 27 Floors          3
18th   of 18 Floors          3
15th   of 40 Floors          3
15th   of 22 Floors          3
3rd   of 8 Floors            3
9th   of 40 Floors           3
31st   of 32 Floors          3
1st   of 11 Floors           3
3rd   of 26 Floors           3
6th   of 23 Floors           3
6th   of 29 Floors           3
18th   of 26 Floors          3
23rd   of 23 Floors          3
21st   of 22 Floors          3
4th   of 16 Floors           3
11st   of 27 Floors          3
2nd   of 22 Floors           3
10th   of 23 Floors          3
6th   of 21 Floors           3
14th   of 32 Floors          3
4th   of 21 Floors           3
21st   of 24 Floors          3
30th   of 32 Floors          3
24th   of 24 Floors          3
5th   of 17 Floors           3
19th   of 21 Floors          3
12nd   of 23 Floors          3
5th   of 26 Floors           3
20th   of 28 Floors          3
Ground of 26 Floors          3
15th   of 20 Floors          3
3rd   of 16 Floors           3
17th   of 30 Floors          3
10th   of 16 Floors          3
8th   of 17 Floors           3
2nd   of 26 Floors           3
9th   of 21 Floors           3
19th   of 29 Floors          3
Ground of 18 Floors          3
8th   of 25 Floors           3
15th   of 39 Floors          3
6th   of 8 Floors            3
8th   of 40 Floors           3
18th   of 30 Floors          3
1st   of 35 Floors           3
4th   of 29 Floors           3
17th   of 29 Floors          3
17th   of 20 Floors          3
4th   of 20 Floors           3
10th   of 28 Floors          3
19th   of 30 Floors          3
27th   of 27 Floors          3
1st   of 17 Floors           2
3rd   of 33 Floors           2
18th   of 21 Floors          2
14th   of 28 Floors          2
16th   of 32 Floors          2
16th   of 27 Floors          2
16th   of 24 Floors          2
2nd   of 6 Floors            2
19th   of 27 Floors          2
7th   of 30 Floors           2
13rd   of 30 Floors          2
10th   of 40 Floors          2
13rd   of 20 Floors          2
2nd   of 28 Floors           2
15th   of 31 Floors          2
27th   of 29 Floors          2
24th   of 30 Floors          2
Ground of 23 Floors          2
4th   of 11 Floors           2
9th   of 29 Floors           2
19th   of 20 Floors          2
2nd   of 24 Floors           2
14th   of 20 Floors          2
43   of 47 Floors            2
1st   of 22 Floors           2
16th   of 30 Floors          2
25th   of 29 Floors          2
23rd   of 29 Floors          2
20th   of 23 Floors          2
9th   of 17 Floors           2
11st   of 23 Floors          2
8th   of 23 Floors           2
8th   of 29 Floors           2
3rd   of 32 Floors           2
10th   of 32 Floors          2
2nd   of 7 Floors            2
4th   of 5 Floors            2
Ground of 51 Floors          2
28th   of 30 Floors          2
7th   of 16 Floors           2
17th   of 23 Floors          2
4th   of 7 Floors            2
15th   of 24 Floors          2
13rd   of 40 Floors          2
8th   of 34 Floors           2
25th   of 30 Floors          2
16th   of 21 Floors          2
7th   of 29 Floors           2
8th   of 32 Floors           2
6th   of 31 Floors           2
12nd   of 25 Floors          2
1st   of 24 Floors           2
39th   of 40 Floors          2
9th   of 28 Floors           2
16th   of 34 Floors          2
10th   of 22 Floors          2
7th   of 36 Floors           2
3rd   of 24 Floors           2
2nd   of 18 Floors           2
2nd   of 40 Floors           2
3rd   of 27 Floors           2
2nd   of 21 Floors           2
10th   of 11 Floors          2
2nd   of 25 Floors           2
1st   of 20 Floors           2
1st   of 30 Floors           2
22nd   of 25 Floors          2
1st   of 8 Floors            2
23rd   of 34 Floors          2
18th   of 24 Floors          2
Lower Ground of 4 Floors     2
4th   of 34 Floors           2
20th   of 25 Floors          2
7th   of 22 Floors           2
3rd   of 29 Floors           2
11st   of 21 Floors          2
8th   of 28 Floors           2
21st   of 27 Floors          2
2nd   of 32 Floors           2
15th   of 17 Floors          2
9th   of 27 Floors           2
20th   of 22 Floors          2
1st   of 16 Floors           2
16th   of 36 Floors          2
5th   of 11 Floors           2
40th   of 40 Floors          2
15th   of 45 Floors          2
17th   of 33 Floors          2
31st   of 40 Floors          1
18th   of 20 Floors          1
3rd   of 31 Floors           1
27th   of 30 Floors          1
34th   of 34 Floors          1
5th   of 36 Floors           1
18th   of 35 Floors          1
17th   of 31 Floors          1
21st   of 23 Floors          1
Ground of 5 Floors           1
Ground of 6 Floors           1
Basement of 13 Floors        1
18th   of 22 Floors          1
17th   of 22 Floors          1
24th   of 36 Floors          1
3rd   of 36 Floors           1
5th   of 6 Floors            1
8th   of 35 Floors           1
Lower Ground of 1 Floors     1
5th   of 35 Floors           1
Ground of 2 Floors           1
10th   of 33 Floors          1
13rd   of 47 Floors          1
34th   of 42 Floors          1
17th   of 21 Floors          1
4th   of 39 Floors           1
24th   of 32 Floors          1
20th   of 34 Floors          1
16th   of 22 Floors          1
18th   of 25 Floors          1
23rd   of 28 Floors          1
8th   of 27 Floors           1
28th   of 29 Floors          1
15th   of 27 Floors          1
11st   of 22 Floors          1
Ground of 11 Floors          1
20th   of 47 Floors          1
27th   of 48 Floors          1
6th   of 7 Floors            1
35th   of 51 Floors          1
22nd   of 28 Floors          1
11st   of 36 Floors          1
28th   of 28 Floors          1
Basement of 4 Floors         1
2nd   of 34 Floors           1
4th   of 40 Floors           1
3rd   of 40 Floors           1
20th   of 32 Floors          1
Basement of 28 Floors        1
19th   of 41 Floors          1
19th   of 26 Floors          1
2nd   of 27 Floors           1
14th   of 51 Floors          1
19th   of 39 Floors          1
12nd   of 39 Floors          1
38th   of 40 Floors          1
18th   of 40 Floors          1
6th   of 25 Floors           1
16th   of 25 Floors          1
4th   of 28 Floors           1
7th   of 32 Floors           1
30th   of 40 Floors          1
4th   of 25 Floors           1
19th   of 23 Floors          1
5th   of 27 Floors           1
24th   of 39 Floors          1
20th   of 30 Floors          1
18th   of 51 Floors          1
24th   of 27 Floors          1
19th   of 22 Floors          1
8th   of 31 Floors           1
33rd   of 48 Floors          1
35th   of 35 Floors          1
26th   of 47 Floors          1
Ground of 24 Floors          1
7th   of 25 Floors           1
20th   of 43 Floors          1
21st   of 51 Floors          1
12nd   of 28 Floors          1
10th   of 34 Floors          1
18th   of 23 Floors          1
12nd   of 32 Floors          1
23rd   of 40 Floors          1
5th   of 32 Floors           1
1st   of 9 Floors            1
3rd   of 6 Floors            1
20th   of 40 Floors          1
9th   of 42 Floors           1
10th   of 51 Floors          1
15th   of 30 Floors          1
21st   of 41 Floors          1
32nd   of 32 Floors          1
8th   of 42 Floors           1
26th   of 34 Floors          1
21st   of 29 Floors          1
20th   of 29 Floors          1
13rd   of 18 Floors          1
7th   of 34 Floors           1
10th   of 39 Floors          1
21st   of 26 Floors          1
1st   of 44 Floors           1
7th   of 42 Floors           1
25th   of 36 Floors          1
21st   of 28 Floors          1
14th   of 22 Floors          1
33rd   of 42 Floors          1
2nd   of 36 Floors           1
19th   of 31 Floors          1
16th   of 51 Floors          1
29th   of 31 Floors          1
22nd   of 40 Floors          1
16th   of 41 Floors          1
7th   of 40 Floors           1
12nd   of 40 Floors          1
3rd   of 28 Floors           1
17th   of 28 Floors          1
3rd   of 30 Floors           1
19th   of 32 Floors          1
16th   of 45 Floors          1
22nd   of 23 Floors          1
7th   of 28 Floors           1
21st   of 36 Floors          1
14th   of 41 Floors          1
Ground of 29 Floors          1
22nd   of 26 Floors          1
32nd   of 55 Floors          1
Ground of 40 Floors          1
13rd   of 22 Floors          1
16th   of 35 Floors          1
44   of 47 Floors            1
23rd   of 24 Floors          1
17th   of 47 Floors          1
4th   of 6 Floors            1
30th   of 34 Floors          1
24th   of 31 Floors          1
24th   of 51 Floors          1
29th   of 29 Floors          1
16th   of 31 Floors          1
5th   of 21 Floors           1
12nd   of 34 Floors          1
5th   of 34 Floors           1
9th   of 25 Floors           1
45   of 47 Floors            1
Ground of 25 Floors          1
9th   of 23 Floors           1
33rd   of 33 Floors          1
1st   of 6 Floors            1
20th   of 24 Floors          1
13rd   of 17 Floors          1
29th   of 39 Floors          1
13rd   of 26 Floors          1
14th   of 25 Floors          1
3rd   of 7 Floors            1
Ground of 22 Floors          1
13rd   of 34 Floors          1
23rd   of 36 Floors          1
Name: count, dtype: int64

In [127]:

df['floorNum'].isnull().sum()

np.int64(2)

In [128]:
df[df['floorNum'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
181,3 BHK Flat in Dwarka Expressway Gurgaon,experion heartsong,1.08,6150.0,Built Up area: 1758 (163.32 sq.m.),3,3,0,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN
2766,2 BHK Flat in Sector 78 Gurgaon,nan,0.60,3692.0,Built Up area: 1625 (150.97 sq.m.),2,2,0,not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [129]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).replace('Ground', '0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

In [130]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [131]:
df.sample(1)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1033,2 BHK Flat in Sector 37C Gurgaon,imperia the esfera,0.87,5513.0,Super Built up area 1578(146.6 sq.m.)Built Up ...,2,3,3+,study room,"D 502, Sector 37C Gurgaon, Gurgaon, Haryana",5,North-West,1 to 5 Year Old,"['Approved Sector 37 Mero Station', 'Esplanade...",Come live in a locale where all your day-To-Da...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."

In [132]:
df['facing'].value_counts()

facing
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [133]:
df['facing'].isnull().sum()

np.int64(874)

In [134]:
df['facing'].fillna('NA',inplace=True)

/var/folders/_8/bm818y_17hq8trchxblt3ct40000gn/T/ipykernel_22269/3692945726.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA',inplace=True)

In [135]:
df['facing'].value_counts()

facing
NA            874
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [136]:
df['facing'].isnull().sum()

np.int64(0)

In [137]:
df.head(1)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [138]:
df.head(2)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [139]:
df.insert(loc=4,column='area',value=round((df['price']*10000000)/df['price_per_sqft']))

In [147]:
df.head(1)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [148]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [149]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2997 entries, 0 to 3016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2997 non-null   object
 1   property_type    2997 non-null   object
 2   society          2997 non-null   object
 3   price            2996 non-null   float64
 4   price_per_sqft   2996 non-null   float64
 5   area             2996 non-null   float64
 6   areaWithType     2997 non-null   object
 7   bedRoom          2997 non-null   int64
 8   bathroom         2997 non-null   int64
 9   balcony          2997 non-null   object
 10  additionalRoom   2997 non-null   object
 11  address          2991 non-null   object
 12  floorNum         2995 non-null   object
 13  facing           2997 non-null   object
 14  agePossession    2996 non-null   object
 15  nearbyLocations  2906 non-null   object
 16  description      2997 non-null   object
 17  furnishDetails   2200 non-null   object
 18  features         2590 non-null   object
 19  rating           2668 non-null   object
dtypes: float64(3), int64(2), object(15)
memory usage: 491.7+ KB

In [150]:
df.shape

(2997, 20)

In [146]:
df.to_csv('flats_cleaned.csv',index=False)